{
  "openapi": "3.0.0",
  "info": {
    "title": "Zoom Contact Center API",
    "description": "Contact Center",
    "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
    "contact": {
      "name": "Zoom Developers",
      "url": "https://developer.zoom.us/"
    },
    "version": "2"
  },
  "servers": [
    {
      "url": "https://api.zoom.us/v2"
    }
  ],
  "paths": {
    "/contact_center/address_books": {
      "get": {
        "tags": [
          "Address Books"
        ],
        "summary": "List address books",
        "description": "Use this API to return all address books. \n\n \n\n**Scopes:** `contact_center_contact:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_address_books:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listAddressBooks",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:read:admin",
              "contact_center:read:list_address_books:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_address_books:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Address Books"
        ],
        "summary": "Create an address book",
        "description": "Use this API to create an [address book](https://support.zoom.us/hc/en-us/articles/4471544949389). An address book is a collection of consumer information like display names, phone numbers, and locations. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:write:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "createAddressBook",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:write:address_book:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:address_book:admin"
          ]
        }
      }
    },
    "/contact_center/address_books/units": {
      "get": {
        "tags": [
          "Address Books"
        ],
        "summary": "List address book units",
        "description": "Use this API to return all address book units. \n\n \n\n**Scopes:** `contact_center_contact:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_address_book_units:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listUnits",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:read:admin",
              "contact_center:read:list_address_book_units:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_address_book_units:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Address Books"
        ],
        "summary": "Create an address book unit",
        "description": "Use this API to create an [address book unit](https://support.zoom.us/hc/en-us/articles/4471495629837-Managing-address-book-units). Admins can use address book units to organize several [address books](https://support.zoom.us/hc/en-us/articles/4471544949389#:~:text=An%20address%20book%20is%20a%20collection%20of%20consumer%20information%20like%20display%20names%2C%20phone%20numbers%2C%20and%20locations.). \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granu[...]",
        "operationId": "createUnit",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:write:address_book_unit:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:address_book_unit:admin"
          ]
        }
      }
    },
    "/contact_center/address_books/units/{unitId}": {
      "get": {
        "tags": [
          "Address Books"
        ],
        "summary": "Get an address book unit",
        "description": "Use this API to get information about an address book unit. \n\n \n\n**Scopes:** `contact_center_contact:read:admin`\n\n**Granular Scopes:** `contact_center:read:address_book_unit:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getUnit",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:read:admin",
              "contact_center:read:address_book_unit:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:address_book_unit:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Address Books"
        ],
        "summary": "Delete an address book unit",
        "description": "Use this API to delete an address book unit. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:delete:address_book_unit:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteUnit",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:delete:address_book_unit:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:address_book_unit:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Address Books"
        ],
        "summary": "Update an address book unit",
        "description": "Use this API to update an address book unit. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:update:address_book_unit:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "updateUnit",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:update:address_book_unit:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:address_book_unit:admin"
          ]
        }
      }
    },
    "/contact_center/address_books/{addressBookId}": {
      "get": {
        "tags": [
          "Address Books"
        ],
        "summary": "Get an address book",
        "description": "Use this API to get information about an address book. \n\n \n\n**Scopes:** `contact_center_contact:read:admin`\n\n**Granular Scopes:** `contact_center:read:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getAddressBook",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:read:admin",
              "contact_center:read:address_book:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:address_book:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Address Books"
        ],
        "summary": "Delete an address book",
        "description": "Use this API to delete an address book. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:delete:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteAddressBook",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:delete:address_book:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:address_book:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Address Books"
        ],
        "summary": "Update an address book",
        "description": "Use this API to update an address book's information. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:update:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "updateAddressBook",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:update:address_book:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:address_book:admin"
          ]
        }
      }
    },
    "/contact_center/address_books/{addressBookId}/contacts": {
      "get": {
        "tags": [
          "Address Books"
        ],
        "summary": "List address book contacts",
        "description": "Returns all contacts in an address book.\n\n**Scopes:** `contact_center_contact:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_address_book_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listContacts",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:read:admin",
              "contact_center:read:list_address_book_contacts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.12.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_contact:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_address_book_contacts:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Address Books"
        ],
        "summary": "Create an address book contact",
        "description": "Use this API to create a new contact in an [address book](https://support.zoom.us/hc/en-us/articles/4471544949389). During an active engagement, the Zoom desktop client will display information from the address book if that customer is a contact in the address book. If the consumer is not in the address book, agents can add a new contact and choose which address book the contact belongs to. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** [...]",
        "operationId": "createContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:write:address_book_contact:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:address_book_contact:admin"
          ]
        }
      }
    },
    "/contact_center/address_books/{addressBookId}/contacts/{contactId}": {
      "get": {
        "tags": [
          "Address Books"
        ],
        "summary": "Get an address book contact",
        "description": "Use this API to get information about an address book's contact. \n\n \n\n**Scopes:** `contact_center_contact:read:admin`\n\n**Granular Scopes:** `contact_center:read:address_book_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:read:admin",
              "contact_center:read:address_book_contact:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-macro-scopes": [
            "contact_center_contact:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:address_book_contact:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Address Books"
        ],
        "summary": "Delete an address book contact",
        "description": "Use this API to delete an address book's contact. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:delete:address_book_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "contactDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:delete:address_book_contact:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:address_book_contact:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Address Books"
        ],
        "summary": "Update an address book contact",
        "description": "Use this API to update an address book's contact. \n\n \n\n**Scopes:** `contact_center_contact:write:admin`\n\n**Granular Scopes:** `contact_center:update:address_book_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "updateContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_contact:write:admin",
              "contact_center:update:address_book_contact:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-macro-scopes": [
            "contact_center_contact:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:address_book_contact:admin"
          ]
        }
      }
    },
    "/contact_center/system_statuses": {
      "get": {
        "tags": [
          "Agent Statuses"
        ],
        "summary": "List system statuses",
        "description": "Get a list of system statuses. Admins can create system statuses, such as **Maintenance**.  \n\n**Scopes:** `contact_center_preference:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_system_statues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listSystemStatus",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_preference:read:admin",
              "contact_center:read:list_system_statues:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.2.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_preference:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_system_statues:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Agent Statuses"
        ],
        "summary": "Create a system status",
        "description": "Create custom statuses for the `agent_status` and `queue_opt_out_and_not_ready_status` categories. \n\n \n\n**Scopes:** `contact_center_preference:write:admin`\n\n**Granular Scopes:** `contact_center:write:system_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createSystemStatus",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_preference:write:admin",
              "contact_center:write:system_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.2.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_preference:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:system_status:admin"
          ]
        }
      }
    },
    "/contact_center/system_statuses/{statusId}": {
      "get": {
        "tags": [
          "Agent Statuses"
        ],
        "summary": "Get a system status",
        "description": "Get information about a system status. \n\n \n\n**Scopes:** `contact_center_preference:read:admin`\n\n**Granular Scopes:** `contact_center:read:system_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getAStatus",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_preference:read:admin",
              "contact_center:read:system_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.2.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_preference:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:system_status:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Agent Statuses"
        ],
        "summary": "Delete a system status",
        "description": "Delete a custom status for the agent_status and queue_opt_out_and_not_ready_status categories.\n\n**Scopes:** `contact_center_preference:write:admin`\n\n**Granular Scopes:** `contact_center:delete:system_status:admin`",
        "operationId": "deleteSystemStatus",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_preference:write:admin",
              "contact_center:delete:system_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.12.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_preference:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:system_status:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Agent Statuses"
        ],
        "summary": "Update a system status",
        "description": "Update a custom status for the `agent_status` and `queue_opt_out_and_not_ready_status` categories. \n\n \n\n**Scopes:** `contact_center_preference:write:admin`\n\n**Granular Scopes:** `contact_center:update:system_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateSystemStatus",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_preference:write:admin",
              "contact_center:update:system_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.2.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_preference:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:system_status:admin"
          ]
        }
      }
    },
    "/contact_center/outbound_campaign/contact_lists": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "List campaign contact lists",
        "description": "List campaign contact lists.\n\n**Scopes:** `contact_center_outbound_campaign_contactlist:read:admin`\n\n**Granular Scopes:** `contact_center:read:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listCampaignContactLists",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contactlist:read:admin",
              "contact_center:read:outbound_campaign_contactlist:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contactlist:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:outbound_campaign_contactlist:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Create a campaign contact list",
        "description": "Create a campaign contact list. Supports only contact list, NOT Do Not Contact Lists\n\n**Scopes:** `contact_center_outbound_campaign_contactlist:write:admin`\n\n**Granular Scopes:** `contact_center:write:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createCampaignContactList",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contactlist:write:admin",
              "contact_center:write:outbound_campaign_contactlist:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contactlist:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:outbound_campaign_contactlist:admin"
          ]
        }
      }
    },
    "/contact_center/outbound_campaign/contact_lists/{contactListId}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Get a campaign contact list",
        "description": "Get a campaign contact list.\n\n**Scopes:** `contact_center_outbound_campaign_contactlist:read:admin`\n\n**Granular Scopes:** `contact_center:read:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getCampaignContactList",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contactlist:read:admin",
              "contact_center:read:outbound_campaign_contactlist:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contactlist:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:outbound_campaign_contactlist:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Campaign"
        ],
        "summary": "Remove campaign contact list",
        "description": "Delete a campaign contact list\n\n**Scopes:** `contact_center_outbound_campaign_contactlist:write:admin`\n\n**Granular Scopes:** `contact_center:delete:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteCampaignContactList",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contactlist:write:admin",
              "contact_center:delete:outbound_campaign_contactlist:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contactlist:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:outbound_campaign_contactlist:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Campaign"
        ],
        "summary": "Update campaign contact list",
        "description": "Update a campaign contact list\n\n**Scopes:** `contact_center_outbound_campaign_contactlist:write:admin`\n\n**Granular Scopes:** `contact_center:update:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateCampaignContactList",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contactlist:write:admin",
              "contact_center:update:outbound_campaign_contactlist:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contactlist:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:outbound_campaign_contactlist:admin"
          ]
        }
      }
    },
    "/contact_center/outbound_campaign/contact_lists/{contactListId}/contacts": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "List a campaign contact list's contacts",
        "description": "List contacts on a campaign contact list.\n\n**Scopes:** `contact_center_outbound_campaign_contacts:read:admin`\n\n**Granular Scopes:** `contact_center:read:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listCampaignContactListContacts",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contacts:read:admin",
              "contact_center:read:outbound_campaign_contacts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contacts:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:outbound_campaign_contacts:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "summary": "Create campaign contact list's contact",
        "description": "Add a new contact to a campaign contact list.\n\n**Scopes:** `contact_center_outbound_campaign_contacts:write:admin`\n\n**Granular Scopes:** `contact_center:write:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createCampaignContactListContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contacts:write:admin",
              "contact_center:write:outbound_campaign_contacts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contacts:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:outbound_campaign_contacts:admin"
          ]
        }
      }
    },
    "/contact_center/outbound_campaign/contact_lists/{contactListId}/contacts/{contactId}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "summary": "Get a campaign contact list's contact",
        "description": "Get a contact on a campaign contact list.\n\n**Scopes:** `contact_center_outbound_campaign_contacts:read:admin`\n\n**Granular Scopes:** `contact_center:read:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getCampaignContactListContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contacts:read:admin",
              "contact_center:read:outbound_campaign_contacts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contacts:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:outbound_campaign_contacts:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Campaign"
        ],
        "summary": "Remove contact from a campaign contact list",
        "description": "Remove a contact by ID from a campaign contact list.\n\n**Scopes:** `contact_center_outbound_campaign_contacts:write:admin`\n\n**Granular Scopes:** `contact_center:delete:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteCampaigncontactListContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contacts:write:admin",
              "contact_center:delete:outbound_campaign_contacts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contacts:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:outbound_campaign_contacts:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Campaign"
        ],
        "summary": "Update contact on a campaign contact list",
        "description": "Update a contact on a campaign contact list.\n\n**Scopes:** `contact_center_outbound_campaign_contacts:write:admin`\n\n**Granular Scopes:** `contact_center:update:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateCampaignContactListContact",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_outbound_campaign_contacts:write:admin",
              "contact_center:update:outbound_campaign_contacts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_outbound_campaign_contacts:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:outbound_campaign_contacts:admin"
          ]
        }
      }
    },
    "/contact_center/dispositions": {
      "get": {
        "tags": [
          "Dispositions"
        ],
        "summary": "List dispositions",
        "description": "Return a list of available dispositions. \n\n \n\n**Scopes:** `contact_center_disposition:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_dispositions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listDispositions",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:read:admin",
              "contact_center:read:list_dispositions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.1.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_disposition:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_dispositions:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Create a disposition",
        "description": "Create a new [disposition](https://support.zoom.us/hc/en-us/articles/4470153057549-Managing-dispositions). Dispositions let agents assign an outcome or topic to each engagement. After creating dispositions, you can add them to queues. \n\n \n\n**Scopes:** `contact_center_disposition:write:admin`\n\n**Granular Scopes:** `contact_center:write:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createDisposition",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:write:admin",
              "contact_center:write:disposition:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.1.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_disposition:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:disposition:admin"
          ]
        }
      }
    },
    "/contact_center/dispositions/sets": {
      "get": {
        "tags": [
          "Dispositions"
        ],
        "summary": "List disposition sets",
        "description": "Return a list of available disposition sets. You can use sets to organize dispositions into groups. \n\n \n\n**Scopes:** `contact_center_disposition:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_disposition_sets:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listSets",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:read:admin",
              "contact_center:read:list_disposition_sets:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_disposition:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_disposition_sets:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Create a disposition set",
        "description": "Create a new disposition set. \n\n \n\n**Scopes:** `contact_center_disposition:write:admin`\n\n**Granular Scopes:** `contact_center:write:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "createSet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:write:admin",
              "contact_center:write:disposition_set:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_disposition:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:disposition_set:admin"
          ]
        }
      }
    },
    "/contact_center/dispositions/sets/{dispositionSetId}": {
      "get": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Get a disposition set",
        "description": "Retrieve information about a disposition set. \n\n \n\n**Scopes:** `contact_center_disposition:read:admin`\n\n**Granular Scopes:** `contact_center:read:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:read:admin",
              "contact_center:read:disposition_set:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_disposition:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:disposition_set:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Delete a disposition set",
        "description": "Delete a disposition set. \n\n \n\n**Scopes:** `contact_center_disposition:write:admin`\n\n**Granular Scopes:** `contact_center:delete:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteSet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:write:admin",
              "contact_center:delete:disposition_set:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_disposition:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:disposition_set:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Update a disposition set",
        "description": "Update an existing disposition set. \n\n \n\n**Scopes:** `contact_center_disposition:write:admin`\n\n**Granular Scopes:** `contact_center:update:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "updateSet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:write:admin",
              "contact_center:update:disposition_set:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_disposition:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:disposition_set:admin"
          ]
        }
      }
    },
    "/contact_center/dispositions/{dispositionId}": {
      "get": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Get a disposition",
        "description": "Retrieve information about a disposition. \n\n \n\n**Scopes:** `contact_center_disposition:read:admin`\n\n**Granular Scopes:** `contact_center:read:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getDisposition",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:read:admin",
              "contact_center:read:disposition:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.1.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_disposition:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:disposition:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Delete a disposition",
        "description": "Delete an existing disposition. \n\n \n\n**Scopes:** `contact_center_disposition:write:admin`\n\n**Granular Scopes:** `contact_center:delete:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteDisposition",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:write:admin",
              "contact_center:delete:disposition:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_disposition:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:disposition:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Dispositions"
        ],
        "summary": "Update a disposition",
        "description": "Update an existing disposition. \n\n \n\n**Scopes:** `contact_center_disposition:write:admin`\n\n**Granular Scopes:** `contact_center:update:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateDisposition",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_disposition:write:admin",
              "contact_center:update:disposition:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.3.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_disposition:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:disposition:admin"
          ]
        }
      }
    },
    "/contact_center/engagements": {
      "get": {
        "tags": [
          "Engagements"
        ],
        "summary": "List engagements",
        "description": "Returns a list of engagements.\n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_engagements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listEngagements",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:list_engagements:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_engagements:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/{engagementId}": {
      "get": {
        "tags": [
          "Engagements"
        ],
        "summary": "Get an engagement",
        "description": "Retrieve information about an engagement.\n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEngagement",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:engagement:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:engagement:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/{engagementId}/recording/{command}": {
      "put": {
        "tags": [
          "Engagements"
        ],
        "summary": "Control an engagement's recording",
        "description": "Controls the recording state for an engagement.\n\nThis request is only valid for video and voice engagements. Calling this API for other channel types is invalid.\n\nAcceptance of a request and response of `HTTP 204 No Content` only ensures there were no validation errors with the request.\n\n**Scopes:** `contact_center_engagement:write:admin`\n\n**Granular Scopes:** `contact_center:update:engagement_recording_control:admin`\n\n**[Rate Limit Label](https://marketplace.zo[...]",
        "operationId": "engagementRecordingControl",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_engagement:write:admin",
              "contact_center:update:engagement_recording_control:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_engagement:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:engagement_recording_control:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/{engagementId}/recordings/status": {
      "get": {
        "tags": [
          "Engagements"
        ],
        "summary": "Poll an engagement recording's status",
        "description": "Polls a video or voice engagement's recordings' status.\n\n**Scopes:** `contact_center_engagement:read:admin`\n\n**Granular Scopes:** `contact_center:read:engagement_recording_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "EngagementRecordingStatus",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_engagement:read:admin",
              "contact_center:read:engagement_recording_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_engagement:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:engagement_recording_status:admin"
          ]
        }
      }
    },
    "/contact_center/flows": {
      "get": {
        "tags": [
          "Flows"
        ],
        "summary": "List flows",
        "description": "Return a list of flows. \n\n \n\n**Scopes:** `contact_center_flow:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_flows:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listFlows",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_flow:read:admin",
              "contact_center:read:list_flows:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_flow:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_flows:admin"
          ]
        }
      }
    },
    "/contact_center/flows/{flowId}": {
      "get": {
        "tags": [
          "Flows"
        ],
        "summary": "Get a flow",
        "description": "Get information about a flow. \n\n \n\n**Scopes:** `contact_center_flow:read:admin`\n\n**Granular Scopes:** `contact_center:read:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getAFlow",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_flow:read:admin",
              "contact_center:read:flow:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_flow:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:flow:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes": {
      "get": {
        "tags": [
          "Inboxes"
        ],
        "summary": "List inboxes",
        "description": "Return a list of inboxes. \n\n \n\n**Scopes:** `contact_center_inbox:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_inboxes:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listInbox",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:read:admin",
              "contact_center:read:list_inboxes:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_inboxes:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Create an inbox",
        "description": "Create a new inbox. \n\n \n\n**Scopes:** `contact_center_inbox:write:admin`\n\n**Granular Scopes:** `contact_center:write:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "inboxCreate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:write:admin",
              "contact_center:write:inbox:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:inbox:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Delete inboxes",
        "description": "Delete one or more inboxes. \n\n \n\n**Scopes:** `contact_center_inbox:write:admin`\n\n**Granular Scopes:** `contact_center:delete:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "inboxesDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:write:admin",
              "contact_center:delete:inbox:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:inbox:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes/messages": {
      "get": {
        "tags": [
          "Inboxes"
        ],
        "summary": "List an account's inbox messages",
        "description": "Return all messages in an inbox. \n\n \n\n**Scopes:** `contact_center_inbox:read:admin`\n\n**Granular Scopes:** `contact_center:read:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listInboxesMessages",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:read:admin",
              "contact_center:read:inbox_messages:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_inbox:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:inbox_messages:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Delete inbox messages",
        "description": "Delete messages. \n\n \n\n**Scopes:** `contact_center_inbox:write:admin`\n\n**Granular Scopes:** `contact_center:delete:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "inboxesMessagesDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:write:admin",
              "contact_center:delete:inbox_messages:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_inbox:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:inbox_messages:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes/{inboxId}": {
      "get": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Get an inbox",
        "description": "Retrieve an inbox. \n\n \n\n**Scopes:** `contact_center_inbox:read:admin`\n\n**Granular Scopes:** `contact_center:read:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getInbox",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:read:admin",
              "contact_center:read:inbox:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:inbox:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Update an inbox",
        "description": "Update an inbox. \n\n \n\n**Scopes:** `contact_center_inbox:write:admin`\n\n**Granular Scopes:** `contact_center:update:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "inboxUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:write:admin",
              "contact_center:update:inbox:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:inbox:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes/{inboxId}/messages": {
      "get": {
        "tags": [
          "Inboxes"
        ],
        "summary": "List an inbox's messages",
        "description": "Return a list of all messages in an inbox. \n\n \n\n**Scopes:** `contact_center_inbox:read:admin`\n\n**Granular Scopes:** `contact_center:read:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listInboxMessages",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:read:admin",
              "contact_center:read:inbox_messages:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_inbox:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:inbox_messages:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Delete an inbox's messages",
        "description": "Delete messages in an inbox. \n\n \n\n**Scopes:** `contact_center_inbox:write:admin`\n\n**Granular Scopes:** `contact_center:delete:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "inboxMessagesDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:write:admin",
              "contact_center:delete:inbox_messages:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:inbox_messages:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes/{inboxId}/messages/{messageId}": {
      "delete": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Delete an inbox message",
        "description": "Delete a single message in an inbox. \n\n \n\n**Scopes:** `contact_center_inbox:write:admin`\n\n**Granular Scopes:** `contact_center:delete:inbox_message:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "inboxMessageDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_inbox:write:admin",
              "contact_center:delete:inbox_message:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_inbox:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:inbox_message:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes/{inboxId}/queues": {
      "get": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Get inbox access queues",
        "description": "Retrieve a list of queues that have access to an inbox. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_inbox_queues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listInboxQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:list_inbox_queues:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_inbox_queues:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Assign inbox access queues",
        "description": "Assign queues access to an inbox. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:write:inbox_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "assignInboxQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:write:inbox_queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:inbox_queue:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Remove inbox access queues",
        "description": "Remove queues' access to an inbox. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:inbox_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "unassignInboxQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:inbox_queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:inbox_queue:admin"
          ]
        }
      }
    },
    "/contact_center/inboxes/{inboxId}/users": {
      "get": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Get an inbox's users",
        "description": "Retrieve a list of users assigned to an inbox. \n\n \n\n**Scopes:** `contact_center_user:read:admin`\n\n**Granular Scopes:** `contact_center:read:inbox_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listInboxUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:read:admin",
              "contact_center:read:inbox_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_user:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:inbox_user:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Assign inbox access users",
        "description": "Assign a user's access to an inbox. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:write:inbox_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "assignInboxUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:write:inbox_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:inbox_user:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Inboxes"
        ],
        "summary": "Unassign inbox access users",
        "description": "Remove users' access to an inbox. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:delete:inbox_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "unassignInboxUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:delete:inbox_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:inbox_user:admin"
          ]
        }
      }
    },
    "/contact_center/sms": {
      "get": {
        "tags": [
          "Logs"
        ],
        "summary": "List SMS logs",
        "description": "Returns a list of SMS. \n\n \n\n**Scopes:** `contact_center_sms:read:admin`\n\n**Granular Scopes:** `contact_center:read:sms_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listSMS",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_sms:read:admin",
              "contact_center:read:sms_log:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_sms:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:sms_log:admin"
          ]
        }
      }
    },
    "/contact_center/voice_calls": {
      "get": {
        "tags": [
          "Logs"
        ],
        "summary": "List voice call logs",
        "description": "Returns a list of voice call logs. \n\n \n\n**Scopes:** `contact_center_voice_call:read:admin`\n\n**Granular Scopes:** `contact_center:read:voice_call_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listVoiceCall",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_voice_call:read:admin",
              "contact_center:read:voice_call_log:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_voice_call:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:voice_call_log:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/notes": {
      "get": {
        "tags": [
          "Notes"
        ],
        "summary": "List notes",
        "description": "Return a list of notes. \n\n \n\n**Scopes:** `contact_center_note:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_notes:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "notes",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_note:read:admin",
              "contact_center:read:list_notes:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_note:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_notes:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/{engagementId}/notes": {
      "get": {
        "tags": [
          "Notes"
        ],
        "summary": "List engagement notes",
        "description": "Return a list of notes under an engagement. \n\n \n\n**Scopes:** `contact_center_note:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_notes:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "engagementNotes",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_note:read:admin",
              "contact_center:read:list_notes:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_note:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_notes:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/{engagementId}/notes/{noteId}": {
      "get": {
        "tags": [
          "Notes"
        ],
        "summary": "Get a note",
        "description": "Retrieve a note. \n\n \n\n**Scopes:** `contact_center_note:read:admin`\n\n**Granular Scopes:** `contact_center:read:note:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getNote",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_note:read:admin",
              "contact_center:read:note:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_note:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:note:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Notes"
        ],
        "summary": "Update a note",
        "description": "Update a note. \n\n \n\n**Scopes:** `contact_center_note:write`\n\n**Granular Scopes:** `contact_center:update:note`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "noteUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_note:write",
              "contact_center:update:note"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_note:write"
          ],
          "x-granular-scopes": [
            "contact_center:update:note"
          ]
        }
      }
    },
    "/contact_center/business_hours": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "List business hours",
        "description": "Get a list of business hours. Admins can create business hours to select, such as the business hours &quot;Default Hours&quot;. \n\n \n\n**Scopes:** `contact_center_operating_hours:read:admin`,`contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_business_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listBusinessHours",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:read:admin",
              "contact_center_queue:read:admin",
              "contact_center:read:list_business_hours:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_operating_hours:read:admin",
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_business_hours:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Create business hours",
        "description": "Create new business hours. \n\n \n\n**Scopes:** `contact_center_operating_hours:write:admin`,`contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:write:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "businessHourCreate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:write:admin",
              "contact_center_queue:write:admin",
              "contact_center:write:business_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_operating_hours:write:admin",
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:business_hour:admin"
          ]
        }
      }
    },
    "/contact_center/business_hours/{businessHourId}": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Get business hours",
        "description": "Get information about business hours. \n\n \n\n**Scopes:** `contact_center_operating_hours:read:admin`,`contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getABusinessHour",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:read:admin",
              "contact_center_queue:read:admin",
              "contact_center:read:business_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_operating_hours:read:admin",
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:business_hour:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Delete business hours",
        "description": "Delete business hours. \n\n \n\n**Scopes:** `contact_center_operating_hours:write:admin`\n\n**Granular Scopes:** `contact_center:delete:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "businessHourDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:write:admin",
              "contact_center:delete:business_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_operating_hours:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:business_hour:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Update business hours",
        "description": "Update business hours.   \n   \n \n\n\n**Scopes:** `contact_center_operating_hours:write:admin`\n\n**Granular Scopes:** `contact_center:update:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "businessHourUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:write:admin",
              "contact_center:update:business_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_operating_hours:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:business_hour:admin"
          ]
        }
      }
    },
    "/contact_center/business_hours/{businessHourId}/flows": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "List the business hours' flows",
        "description": "Show a list of flows using business hours. \n\n \n\n**Scopes:** `contact_center_flow:read:admin`\n\n**Granular Scopes:** `contact_center:read:business_hours_flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "listBusinessHourFlows",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_flow:read:admin",
              "contact_center:read:business_hours_flow:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_flow:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:business_hours_flow:admin"
          ]
        }
      }
    },
    "/contact_center/business_hours/{businessHourId}/queues": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "List the business hours' queues",
        "description": "Show a list of queues using business hours. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:business_hours_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "listBusinessHourQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:business_hours_queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:business_hours_queue:admin"
          ]
        }
      }
    },
    "/contact_center/closures": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "List closures",
        "description": "Get a list of closures. Admins can create closures to select. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`,`contact_center_operating_hours:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_closure_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listClosures",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center_operating_hours:read:admin",
              "contact_center:read:list_closure_hours:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin",
            "contact_center_operating_hours:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_closure_hours:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Create a closure set",
        "description": "Create a new closure set. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`,`contact_center_operating_hours:write:admin`\n\n**Granular Scopes:** `contact_center:write:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "closuresSetCreate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center_operating_hours:write:admin",
              "contact_center:write:closure_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin",
            "contact_center_operating_hours:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:closure_hour:admin"
          ]
        }
      }
    },
    "/contact_center/closures/{closureSetId}": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Get a closure set",
        "description": "Get information about a closure set.  \n\n**Scopes:** `contact_center_queue:read:admin`,`contact_center_operating_hours:read:admin`\n\n**Granular Scopes:** `contact_center:read:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getAClosureSet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center_operating_hours:read:admin",
              "contact_center:read:closure_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin",
            "contact_center_operating_hours:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:closure_hour:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Delete a closure set",
        "description": "Delete closure sets. \n\n \n\n**Scopes:** `contact_center_operating_hours:write:admin`\n\n**Granular Scopes:** `contact_center:delete:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "closureSetDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:write:admin",
              "contact_center:delete:closure_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_operating_hours:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:closure_hour:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "Update a closure set",
        "description": "Update information about a closure set.\n\n**Scopes:** `contact_center_operating_hours:write:admin`\n\n**Granular Scopes:** `contact_center:update:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "closureSetUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operating_hours:write:admin",
              "contact_center:update:closure_hour:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_operating_hours:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:closure_hour:admin"
          ]
        }
      }
    },
    "/contact_center/closures/{closureSetId}/flows": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "List the closures' flows",
        "description": "Show a list of flows using closures. \n\n \n\n**Scopes:** `contact_center_flow:read:admin`\n\n**Granular Scopes:** `contact_center:read:clousre_hour_flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "listClosureSetFlows",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_flow:read:admin",
              "contact_center:read:clousre_hour_flow:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_flow:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:clousre_hour_flow:admin"
          ]
        }
      }
    },
    "/contact_center/closures/{closureSetId}/queues": {
      "get": {
        "tags": [
          "Operating Hours"
        ],
        "summary": "List the closures' queues",
        "description": "Show a list of queues using closures. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:closure_hour_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "listClosureSetQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:closure_hour_queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:closure_hour_queue:admin"
          ]
        }
      }
    },
    "/contact_center/queues": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "List queues",
        "description": "Get information about all available queues. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_queues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:list_queues:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0-fix",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_queues:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Queues"
        ],
        "summary": "Create a queue",
        "description": "Create an agent [queue](https://support.zoom.us/hc/en-us/articles/4423986595085) to determine which agents calls are routed to. Queues also link to an existing routing profile to determine how calls are routed. \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:write:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "queueCreate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:write:queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0-fix",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:queue:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "Get a queue",
        "description": "Get information about a queue. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getAQueue",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0-fix",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:queue:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Queues"
        ],
        "summary": "Delete a queue",
        "description": "Delete a specified queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "queueDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Queues"
        ],
        "summary": "Update a queue",
        "description": "Update a queue's description or agent list.   \n   \n \n\n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:update:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "queueUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:update:queue:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0-fix",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:queue:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/agents": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "List queue agents",
        "description": "Retrieve the list of a queue's assigned agents. \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_queue_agents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "getQueueAgents",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:list_queue_agents:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_queue_agents:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Queues"
        ],
        "summary": "Assign queue agents",
        "description": "Add agents to a queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:write:queue_agent:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "assignQueueAgents",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:write:queue_agent:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:queue_agent:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/agents/{userId}": {
      "delete": {
        "tags": [
          "Queues"
        ],
        "summary": "Unassign a queue agent",
        "description": "Remove an agent from a queue. \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:queue_agent:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteQueueAgent",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:queue_agent:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue_agent:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Queues"
        ],
        "summary": "Update a queue agent",
        "description": "Update the list of agents in a queue. \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:update:queue_agent:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateQueueAgent",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:update:queue_agent:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:queue_agent:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/dispositions": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "List queue dispositions",
        "description": "Return a list of queue's [dispositions](https://support.zoom.us/hc/en-us/articles/4470153057549-Managing-dispositions). \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_dispositions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "getQueueDispositions",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:list_dispositions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_dispositions:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Queues"
        ],
        "summary": "Assign queue dispositions",
        "description": "Add dispositions to a queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:write:queue disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "assignQueueDispositions",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:write:queue disposition:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:queue disposition:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/dispositions/sets": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "List queue disposition sets",
        "description": "Return a list of queue's disposition sets(https://support.zoom.us/hc/en-us/articles/4470153057549-Managing-dispositions). \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_disposition_sets:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "getQueueDispositionSets",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:list_disposition_sets:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_disposition_sets:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Queues"
        ],
        "summary": "Assign a queue disposition set",
        "description": "Add a disposition set to a queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:write:queue_disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "assignQueueDispositionSets",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:write:queue_disposition_set:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:queue_disposition_set:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/dispositions/sets/{dispositionSetId}": {
      "delete": {
        "tags": [
          "Queues"
        ],
        "summary": "Unassign a queue disposition set",
        "description": "Delete a disposition set from a queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:queue_disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteQueueDispositionSet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:queue_disposition_set:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue_disposition_set:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/dispositions/{dispositionId}": {
      "delete": {
        "tags": [
          "Queues"
        ],
        "summary": "Unassign a queue disposition",
        "description": "Delete a disposition from a queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:queue_disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteQueueDisposition",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:queue_disposition:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue_disposition:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/operating_hours": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "Get a queue's operating hours",
        "description": "Get information about a queue's operating hours. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:read:queue_operating_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getAQueueOperatingHours",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:read:queue_operating_hours:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:queue_operating_hours:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Queues"
        ],
        "summary": "Update a queue's operating hours",
        "description": "Update a queue's operating hours. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:patch:queue_operating_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "QueueOperatingHoursUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:patch:queue_operating_hours:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:patch:queue_operating_hours:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/supervisors": {
      "get": {
        "tags": [
          "Queues"
        ],
        "summary": "List queue supervisors",
        "description": "Return a list of a queue's assigned supervisors. \n\n \n\n**Scopes:** `contact_center_queue:read:admin`\n\n**Granular Scopes:** `contact_center:delete:queue_supervisor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "getQueueSupervisors",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:read:admin",
              "contact_center:delete:queue_supervisor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue_supervisor:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Queues"
        ],
        "summary": "Assign queue supervisors",
        "description": "Add supervisors to a queue. \n\n \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:queue_supervisor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "assignQueueSupervisors",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:queue_supervisor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue_supervisor:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/supervisors/{userId}": {
      "delete": {
        "tags": [
          "Queues"
        ],
        "summary": "Unassign a queue supervisor",
        "description": "Remove a supervisor from a queue. \n\n**Scopes:** `contact_center_queue:write:admin`\n\n**Granular Scopes:** `contact_center:delete:queue_supervisor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteQueueSupervisor",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_queue:write:admin",
              "contact_center:delete:queue_supervisor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_queue:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:queue_supervisor:admin"
          ]
        }
      }
    },
    "/contact_center/engagements/{engagementId}/recordings": {
      "get": {
        "tags": [
          "Recordings"
        ],
        "summary": "List engagement recordings",
        "description": "Return a list of all of an engagement's recordings. \n\n**Note:** Use recording-related APIs to manipulate data whose recording was created after July 18, 2022. \n\n \n\n**Scopes:** `contact_center_recording:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_recordings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listEngagementRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:read:admin",
              "contact_center:read:list_recordings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_recording:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_recordings:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Recordings"
        ],
        "summary": "Delete engagement recordings",
        "description": "Delete all recordings in a given engagement.  \n\n**Note**: Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**Scopes:** `contact_center_recording:write:admin`\n\n**Granular Scopes:** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteEngagementRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:write:admin",
              "contact_center:delete:recording:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_recording:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:recording:admin"
          ]
        }
      }
    },
    "/contact_center/queues/{queueId}/recordings": {
      "get": {
        "tags": [
          "Recordings"
        ],
        "summary": "List queue recordings",
        "description": "Return a list of all recordings in a queue. \n\n**Note:** Use recording-related APIs to manipulate data whose recording was created after July 18, 2022. \n\n \n\n**Scopes:** `contact_center_recording:read:admin`,`contact_center_recording:read`\n\n**Granular Scopes:** `contact_center:read:list_recordings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listQueueRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:read:admin",
              "contact_center_recording:read",
              "contact_center:read:list_recordings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_recording:read:admin",
            "contact_center_recording:read"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_recordings:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Recordings"
        ],
        "summary": "Delete queue recordings",
        "description": "Delete all recordings in a queue. \n\n**Note**: Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**Scopes:** `contact_center_recording:write:admin`\n\n**Granular Scopes:** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteQueueRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:write:admin",
              "contact_center:delete:recording:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_recording:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:recording:admin"
          ]
        }
      }
    },
    "/contact_center/recordings": {
      "get": {
        "tags": [
          "Recordings"
        ],
        "summary": "List recordings",
        "description": "Return a list of available recordings. \n\n**Note** Use recording-related APIs to manipulate data whose recording was created after July 18, 2022. \n\n \n\n**Scopes:** `contact_center_recording:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_recordings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:read:admin",
              "contact_center:read:list_recordings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_recording:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_recordings:admin"
          ]
        }
      }
    },
    "/contact_center/recordings/{recordingId}": {
      "delete": {
        "tags": [
          "Recordings"
        ],
        "summary": "Delete a recording",
        "description": "Delete a selected recording. \n\n**Note**: Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**Scopes:** `contact_center_recording:write:admin`\n\n**Granular Scopes:** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteRecording",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:write:admin",
              "contact_center:delete:recording:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_recording:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:recording:admin"
          ]
        }
      }
    },
    "/contact_center/users/{userId}/recordings": {
      "get": {
        "tags": [
          "Recordings"
        ],
        "summary": "List user's recordings",
        "description": "Get a user's recordings. \n\n**Note** Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**Scopes:** `contact_center_recording:read`,`contact_center_recording:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_recordings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listUserRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:read",
              "contact_center_recording:read:admin",
              "contact_center:read:list_recordings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_recording:read",
            "contact_center_recording:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_recordings:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Recordings"
        ],
        "summary": "Delete user's recordings",
        "description": "Delete all of a given user's recordings.  \n\n**Note** Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**Scopes:** `contact_center_recording:write:admin`\n\n**Granular Scopes:** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteUserRecordings",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_recording:write:admin",
              "contact_center:delete:recording:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "docfix-DEVELOPERS-4191-LS",
          "x-macro-scopes": [
            "contact_center_recording:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:recording:admin"
          ]
        }
      }
    },
    "/contact_center/regions": {
      "get": {
        "tags": [
          "Regions"
        ],
        "summary": "List regions",
        "description": "Get information about all available regions.\n\n**Scopes:** `contact_center_region:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_regions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "ListRegions",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:read:admin",
              "contact_center:read:list_regions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_regions:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Regions"
        ],
        "summary": "Create a region",
        "description": "Create a new region.  \n\n**Scopes:** `contact_center_region:write:admin`\n\n**Granular Scopes:** `contact_center:write:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "CreateARegion",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:write:admin",
              "contact_center:write:region:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:region:admin"
          ]
        }
      }
    },
    "/contact_center/regions/{regionId}": {
      "get": {
        "tags": [
          "Regions"
        ],
        "summary": "Get a region",
        "description": "Get information about a region.  \n\n**Scopes:** `contact_center_region:read:admin`\n\n**Granular Scopes:** `contact_center:read:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "GetARegion",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:read:admin",
              "contact_center:read:region:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:region:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Regions"
        ],
        "summary": "Delete a region",
        "description": "Delete a site and move its members to another region.   \n\n**Scopes:** `contact_center_region:write:admin`\n\n**Granular Scopes:** `contact_center:delete:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "DeleteARegion",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:write:admin",
              "contact_center:delete:region:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:region:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Regions"
        ],
        "summary": "Update a region",
        "description": "Update information for a region.\n\n**Scopes:** `contact_center_region:write:admin`\n\n**Granular Scopes:** `contact_center:udpate:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "UpdateARegion",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:write:admin",
              "contact_center:udpate:region:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:udpate:region:admin"
          ]
        }
      }
    },
    "/contact_center/regions/{regionId}/users": {
      "get": {
        "tags": [
          "Regions"
        ],
        "summary": "List a region's users",
        "description": "Retrieve the list of a region's assigned agents. \n\n \n\n**Scopes:** `contact_center_region:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_region_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "ListRegion'sUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:read:admin",
              "contact_center:read:list_region_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_region_users:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Regions"
        ],
        "summary": "Assign users to a region",
        "description": "Assign users to a region.\n\n**Scopes:** `contact_center_region:write:admin`\n\n**Granular Scopes:** `contact_center:write:region_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "AssignUsersToARegion",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_region:write:admin",
              "contact_center:write:region_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_region:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:region_user:admin"
          ]
        }
      }
    },
    "/contact_center/analytics/agents/status_history": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "List agent's status history reports",
        "description": "Generate a list of an agent's status history reports. \n\n \n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:agent_status_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listAgentStatusHistory",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:agent_status_report:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:agent_status_report:admin"
          ]
        }
      }
    },
    "/contact_center/analytics/agents/time_sheets": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "List agent's time sheet reports",
        "description": "Generate a list of an agent's time sheet reports. \n\n \n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:agent_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listAgentTimeSheet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:agent_report:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "docfix-DEVELOPERS-4191-LS",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:agent_report:admin"
          ]
        }
      }
    },
    "/contact_center/analytics/historical/details/metrics": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "List historical detail reports",
        "description": "Generates a list of historical detail reports.  \n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:engagement_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listHistoricalDetailMetric",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:engagement_report:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:engagement_report:admin"
          ]
        }
      }
    },
    "/contact_center/analytics/historical/queues/metrics": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "List historical queue reports",
        "description": "Generate a list of historical queue reports. \n\n \n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:queue_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listHistoricalQueueMetric",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:queue_report:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:queue_report:admin"
          ]
        }
      }
    },
    "/contact_center/analytics/historical/queues/{queueId}/agents/metrics": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "List historical queue's agents reports",
        "description": "Generate a list of a historical queue's agent reports.  \n\n**Scopes:** `contact_center_report:read:admin`\n\n**Granular Scopes:** `contact_center:read:agent_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listQueueAgentMetric",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_report:read:admin",
              "contact_center:read:agent_report:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_report:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:agent_report:admin"
          ]
        }
      }
    },
    "/contact_center/reports/operation_logs": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "List operation logs",
        "description": "Retrieve the Zoom Contact Center management system operation logs report. \n\n The Zoom Contact Center management system operation logs report lets account owners and admins view monthly Zoom Contact Center related admin operation details.\n\n**Scopes:** `contact_center_operation_logs:read:admin`\n\n**Granular Scopes:** `contact_center:read:operation_logs:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listOperationLogs",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_operation_logs:read:admin",
              "contact_center:read:operation_logs:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "lateMissedRelease-June2024",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_operation_logs:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:operation_logs:admin"
          ]
        }
      }
    },
    "/contact_center/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List roles",
        "description": "Use this API to return a list of roles. \n\n \n\n**Scopes:** `contact_center_role:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_roles:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listRoles",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:read:admin",
              "contact_center:read:list_roles:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_roles:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Roles"
        ],
        "summary": "Create a role",
        "description": "Use this API to create a new [role](https://support.zoom.us/hc/en-us/articles/4471054202253-Using-role-management). Admins can use the role management feature to control access to features and settings in the Zoom web portal. \n\n \n\n**Scopes:** `contact_center_role:write:admin`\n\n**Granular Scopes:** `contact_center:write:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "createRole",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:write:admin",
              "contact_center:write:role:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:role:admin"
          ]
        }
      }
    },
    "/contact_center/roles/{roleId}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get a role",
        "description": "Use this API to get information about a role. \n\n \n\n**Scopes:** `contact_center_role:read:admin`\n\n**Granular Scopes:** `contact_center:read:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getRole",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:read:admin",
              "contact_center:read:role:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:role:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Delete a role",
        "description": "Use this API to delete a role. \n\n \n\n**Scopes:** `contact_center_role:write:admin`\n\n**Granular Scopes:** `contact_center:delete:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteRole",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:write:admin",
              "contact_center:delete:role:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:role:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Roles"
        ],
        "summary": "Update a role",
        "description": "Use this API to update a role. \n\n \n\n**Scopes:** `contact_center_role:write:admin`\n\n**Granular Scopes:** `contact_center:update:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "updateRole",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:write:admin",
              "contact_center:update:role:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:role:admin"
          ]
        }
      }
    },
    "/contact_center/roles/{roleId}/users": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List users of a role",
        "description": "Use this API to get information about the users assigned to a specific role. \n\n \n\n**Scopes:** `contact_center_role:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_role_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "getRoleUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:read:admin",
              "contact_center:read:list_role_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_role_users:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Roles"
        ],
        "summary": "Assign a role",
        "description": "Use this API to assign users to a role. Roles have unique privileges that assigned users have access to. For example, an Administrator or Agent role. \n\n \n\n**Scopes:** `contact_center_role:write:admin`\n\n**Granular Scopes:** `contact_center:write:role_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "assignRoleUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:write:admin",
              "contact_center:write:role_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_role:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:role_user:admin"
          ]
        }
      }
    },
    "/contact_center/roles/{roleId}/users/{userId}": {
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Unassign a role",
        "description": "Use this API to unassign a user from a role. \n\n \n\n**Scopes:** `contact_center_role:write:admin`\n\n**Granular Scopes:** `contact_center:delete:role_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteRoleUser",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_role:write:admin",
              "contact_center:delete:role_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.12.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_role:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:role_user:admin"
          ]
        }
      }
    },
    "/contact_center/agent_routing_profiles/{agentRoutingProfileId}": {
      "get": {
        "tags": [
          "Routing Profiles"
        ],
        "summary": "Get an agent routing profile",
        "description": "Retrieve the agent routing profile. \n\n \n\n**Scopes:** `contact_center_routing_profile:read:admin`\n\n**Granular Scopes:** `contact_center:read:agent_routing_profile:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getAgentRoutingProfile",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_routing_profile:read:admin",
              "contact_center:read:agent_routing_profile:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.7.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_routing_profile:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:agent_routing_profile:admin"
          ]
        }
      }
    },
    "/contact_center/skills": {
      "get": {
        "tags": [
          "Skills"
        ],
        "summary": "List skills",
        "description": "Return a list of a skills or a skill category's assigned skills. \n\n \n\n**Scopes:** `contact_center_skill:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_skills:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listSkills",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:read:admin",
              "contact_center:read:list_skills:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_skills:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Skills"
        ],
        "summary": "Create a skill",
        "description": "Create a [skill](https://support.zoom.us/hc/en-us/articles/4423986613261) for skill-based routing. Skills are agent traits that ensure they are the right person to handle a customer interaction. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:write:skill:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "skillCreate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:write:skill:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:skill:admin"
          ]
        }
      }
    },
    "/contact_center/skills/categories": {
      "get": {
        "tags": [
          "Skills"
        ],
        "summary": "List skill categories",
        "description": "List all available skill categories and their information. \n\n \n\n**Scopes:** `contact_center_skill:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_skill_categories:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listSkillCategory",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:read:admin",
              "contact_center:read:list_skill_categories:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_skill_categories:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Skills"
        ],
        "summary": "Create a skill category",
        "description": "Create a new skill category. Skill categories let you assign several similar skills to a category, such as language skills. You can then route French-speaking callers to contact center agents that have the highest proficiency with French. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:write:skill_category:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "SkillCategoryCreate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:write:skill_category:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:skill_category:admin"
          ]
        }
      }
    },
    "/contact_center/skills/categories/{skillCategoryId}": {
      "get": {
        "tags": [
          "Skills"
        ],
        "summary": "Get a skill category",
        "description": "Return information about a specific skill category. \n\n \n\n**Scopes:** `contact_center_skill:read:admin`\n\n**Granular Scopes:** `contact_center:read:skill_category:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getSkillCategory",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:read:admin",
              "contact_center:read:skill_category:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:skill_category:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Skills"
        ],
        "summary": "Delete a skill category",
        "description": "Delete an existing skill category. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:delete:skill_category:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "SkillCategoryDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:delete:skill_category:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:skill_category:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Skills"
        ],
        "summary": "Update a skill category",
        "description": "Update a skill category. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:update:skill_category:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "SkillCategoryUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:update:skill_category:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:skill_category:admin"
          ]
        }
      }
    },
    "/contact_center/skills/{skillId}": {
      "get": {
        "tags": [
          "Skills"
        ],
        "summary": "Get a skill",
        "description": "Return a skill's information and its usage. \n\n \n\n**Scopes:** `contact_center_skill:read:admin`\n\n**Granular Scopes:** `contact_center:read:skill:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getSkill",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:read:admin",
              "contact_center:read:skill:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:skill:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Skills"
        ],
        "summary": "Delete a skill",
        "description": "Delete a skill. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:delete:skill:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "skillDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:delete:skill:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:skill:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Skills"
        ],
        "summary": "Update a skill",
        "description": "Use this API to update a skill's name. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:update:skill:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "skillNameUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:update:skill:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:skill:admin"
          ]
        }
      }
    },
    "/contact_center/skills/{skillId}/users": {
      "get": {
        "tags": [
          "Skills"
        ],
        "summary": "List users of a skill",
        "description": "Retrieve a list of all users assigned to a skill. \n\n**This endpoint will be deprecated in August 2024.**\n\n**Scopes:** `contact_center_user:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_skill_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listSkillUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:read:admin",
              "contact_center:read:list_skill_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "docfix-DEVELOPERS-4643-LS",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_skill_users:admin"
          ]
        }
      }
    },
    "/contact_center/skills/{skillId}/users/{userId}": {
      "get": {
        "tags": [
          "Skills"
        ],
        "summary": "Get a skill's user",
        "description": "Retrieve information for a particular skill's user. \n\n **This endpoint will be deprecated in August 2024.** For more information, see the [Tasks and Skills deprecation FAQ](https://developers.zoom.us/docs/api/rest/contact-center-api/endpoint-deprecation-faq/#task-and-skill-endpoint-deprecations---august-2024).\n\n\n\n**Scopes:** `contact_center_user:read:admin`\n\n**Granular Scopes:** `contact_center:read:skill_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoo[...]",
        "operationId": "GetASkillUser",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:read:admin",
              "contact_center:read:skill_user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.11.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:skill_user:admin"
          ]
        }
      }
    },
    "/contact_center/tasks": {
      "get": {
        "tags": [
          "Tasks"
        ],
        "summary": "List tasks",
        "description": "Use this API to return a list of tasks. \n\n**This endpoint will be deprecated in August 2024.**\n\n**Scopes:** `contact_center_task:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_tasks:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listTasks",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "contact_center_task:read:admin",
              "contact_center:read:list_tasks:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.11.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_task:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_tasks:admin"
          ]
        }
      }
    },
    "/contact_center/tasks/{taskId}": {
      "get": {
        "tags": [
          "Tasks"
        ],
        "summary": "Get a task",
        "description": "Use this API to return information about a task. \n\n**This endpoint will be deprecated in August 2024.**\n\n**Scopes:** `contact_center_task:read:admin`\n\n**Granular Scopes:** `contact_center:read:task:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getATask",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "contact_center_task:read:admin",
              "contact_center:read:task:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.11.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_task:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:task:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Tasks"
        ],
        "summary": "Update a task",
        "description": "Use this API to:   \n  1) update a task's priority level or   \n  2) manually assign or unassign a task to an agent. \n\n**This endpoint will be deprecated in August 2024.**\n\n**Scopes:** `contact_center_task:write:admin`\n\n**Granular Scopes:** `contact_center:update:task:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "taskUpdate",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "contact_center_task:write:admin",
              "contact_center:update:task:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.11.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_task:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:task:admin"
          ]
        }
      }
    },
    "/contact_center/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "List users' profiles",
        "description": "Returns a list of users and their information. \n\n \n\n**Scopes:** `contact_center_user:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "users",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:read:admin",
              "contact_center:read:list_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.4.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_users:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create a user's profile",
        "description": "Create a profile for a user. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:write:user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createUser",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:write:user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:user:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Batch delete user profiles",
        "description": "Batch delete users. \n\n**Note**: Either `user_ids` or `user_emails` needs to be provided. If both `user_ids` and `user_emails` are provided, only `user_ids` will be used, while `user_emails` will be ignored. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:delete:batch_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "batchDeleteUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:delete:batch_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:batch_users:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Batch update user profiles",
        "description": "Batch update user profiles. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:update:batch_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "BatchUpdateUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:update:batch_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:batch_users:admin"
          ]
        }
      }
    },
    "/contact_center/users/batch": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Batch create user profiles",
        "description": "Batch create user profiles. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:write:batch_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "BatchCreateUsers",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:write:batch_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:batch_users:admin"
          ]
        }
      }
    },
    "/contact_center/users/{userId}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get a user's profile",
        "description": "Retrieve a user's profile information.\n\n**Scopes:** `contact_center_user:read:admin`\n\n**Granular Scopes:** `contact_center:read:user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "userGet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:read:admin",
              "contact_center:read:user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "docfix-DEVELOPERS-4829-LS",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:user:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete a user's profile",
        "description": "Delete the specified user's profile. \n\n \n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:delete:user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "userDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:delete:user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:user:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Update a user's profile",
        "description": "Update information in a user's profile.\n\n**Scopes:** `contact_center_user:write:admin`\n\n**Granular Scopes:** `contact_center:update:user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "userUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:write:admin",
              "contact_center:update:user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:user:admin"
          ]
        }
      }
    },
    "/contact_center/users/{userId}/queues": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "List user's queues",
        "description": "List a user's queues. \n\n \n\n**Scopes:** `contact_center_user:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_user_queues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "listUserQueues",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_user:read:admin",
              "contact_center:read:list_user_queues:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 3.5.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_user:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_user_queues:admin"
          ]
        }
      }
    },
    "/contact_center/users/{userId}/skills": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "List user's skills",
        "description": "Get a list of skills assigned to a given user. \n\n \n\n**Scopes:** `contact_center_skill:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_user_skills:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "ListAUserSkills",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:read:admin",
              "contact_center:read:list_user_skills:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_user_skills:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Assign user's skills",
        "description": "Assign [skills](https://support.zoom.us/hc/en-us/articles/4423986613261) to a user. Skills are user traits that ensure that a given agent is the best person to handle a given customer interaction. Proficiency ratings indicate the user's level of expertise or knowledge of that skill. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:write:user_skill:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/r[...]",
        "operationId": "assignSkills",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:write:user_skill:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:user_skill:admin"
          ]
        }
      }
    },
    "/contact_center/users/{userId}/skills/{skillId}": {
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Unassign user's skill",
        "description": "Delete a skill assigned to a given user. \n\n \n\n**Scopes:** `contact_center_skill:write:admin`\n\n**Granular Scopes:** `contact_center:delete:user_skill:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteASkill",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_skill:write:admin",
              "contact_center:delete:user_skill:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_skill:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:user_skill:admin"
          ]
        }
      }
    },
    "/contact_center/variable_logs": {
      "get": {
        "tags": [
          "Variables"
        ],
        "summary": "List variable logs",
        "description": "Return a list of variable logs.\n\n \n\n**Scopes:** `contact_center_variable_log:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_variable_logs:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId": "listVariableLogs",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable_log:read:admin",
              "contact_center:read:list_variable_logs:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_variable_log:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_variable_logs:admin"
          ]
        }
      }
    },
    "/contact_center/variable_logs/{variableLogId}": {
      "get": {
        "tags": [
          "Variables"
        ],
        "summary": "Get a variable log",
        "description": "Get information about a variable log.\n\n \n\n**Scopes:** `contact_center_variable_log:read:admin`\n\n**Granular Scopes:** `contact_center:read:variable_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getVariableLog",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable_log:read:admin",
              "contact_center:read:variable_log:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_variable_log:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:variable_log:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Variables"
        ],
        "summary": "Delete a variable log",
        "description": "Delete a variable log. \n\n \n\n**Scopes:** `contact_center_variable_log:write:admin`\n\n**Granular Scopes:** `contact_center:delete:variable_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "deleteVariableLog",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable_log:write:admin",
              "contact_center:delete:variable_log:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.5.0",
          "x-permissions": [
            "VecVariablesLogDelete:Edit"
          ],
          "x-macro-scopes": [
            "contact_center_variable_log:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:variable_log:admin"
          ]
        }
      }
    },
    "/contact_center/variables": {
      "get": {
        "tags": [
          "Variables"
        ],
        "summary": "List variables",
        "description": "Returns a list of variables for a specific variable group. \n\n \n\n**Scopes:** `contact_center_variable:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_variables:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "variables",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:read:admin",
              "contact_center:read:list_variables:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_variable:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_variables:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Variables"
        ],
        "summary": "Create a variable",
        "description": "Create a new variable.\n\n**Scopes:** `contact_center_variable:write:admin`\n\n**Granular Scopes:** `contact_center:write:variable:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createVariable",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:write:admin",
              "contact_center:write:variable:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_variable:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:variable:admin"
          ]
        }
      }
    },
    "/contact_center/variables/groups": {
      "get": {
        "tags": [
          "Variables"
        ],
        "summary": "List variable groups",
        "description": "Use thi API to return a list of variable groups.\n\n \n\n**Scopes:** `contact_center_variable:read:admin`\n\n**Granular Scopes:** `contact_center:read:list_variable_groups:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId": "listVariableGroups",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:read:admin",
              "contact_center:read:list_variable_groups:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_variable:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:list_variable_groups:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Variables"
        ],
        "summary": "Create a variable group",
        "description": "Create a custom variable group. \n\n \n\n**Scopes:** `contact_center_variable:write:admin`\n\n**Granular Scopes:** `contact_center:write:variable_group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "createVariableGroup",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:write:admin",
              "contact_center:write:variable_group:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_variable:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:write:variable_group:admin"
          ]
        }
      }
    },
    "/contact_center/variables/groups/{variableGroupId}": {
      "get": {
        "tags": [
          "Variables"
        ],
        "summary": "Get a variable group",
        "description": "Get information about a variable group.\n\n \n\n**Scopes:** `contact_center_variable:read:admin`\n\n**Granular Scopes:** `contact_center:read:variable_group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "getAVariableGroup",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:read:admin",
              "contact_center:read:variable_group:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_variable:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:variable_group:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Variables"
        ],
        "summary": "Delete a variable group",
        "description": "Delete a specified variable group. \n\n \n\n**Scopes:** `contact_center_variable:write:admin`\n\n**Granular Scopes:** `contact_center:delete:variable_group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "DeleteGroup",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:write:admin",
              "contact_center:delete:variable_group:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_variable:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:variable_group:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Variables"
        ],
        "summary": "Update a variable group",
        "description": "Update a variable group. \n\n \n\n**Scopes:** `contact_center_variable:write:admin`\n\n**Granular Scopes:** `contact_center:update:variable_group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "updateVariableGroup",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:write:admin",
              "contact_center:update:variable_group:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-macro-scopes": [
            "contact_center_variable:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:variable_group:admin"
          ]
        }
      }
    },
    "/contact_center/variables/{variableId}": {
      "get": {
        "tags": [
          "Variables"
        ],
        "summary": "Get a variable",
        "description": "Retrieve a variable. \n\n \n\n**Scopes:** `contact_center_variable:read:admin`\n\n**Granular Scopes:** `contact_center:read:variable:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "variableGet",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:read:admin",
              "contact_center:read:variable:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_variable:read:admin"
          ],
          "x-granular-scopes": [
            "contact_center:read:variable:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Variables"
        ],
        "summary": "Delete a variable",
        "description": "Delete a variable. \n\n \n\n**Scopes:** `contact_center_variable:write:admin`\n\n**Granular Scopes:** `contact_center:delete:variable:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId": "variableDelete",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:write:admin",
              "contact_center:delete:variable:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "InitFixVersion",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_variable:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:delete:variable:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Variables"
        ],
        "summary": "Update a variable",
        "description": "Update a variable. \n\n \n\n**Scopes:** `contact_center_variable:write:admin`\n\n**Granular Scopes:** `contact_center:update:variable:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "variableUpdate",
        "security": [
          {
            "openapi_oauth": [
              "contact_center_variable:write:admin",
              "contact_center:update:variable:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "ZCC 2.6.0",
          "x-permissions": [],
          "x-macro-scopes": [
            "contact_center_variable:write:admin"
          ],
          "x-granular-scopes": [
            "contact_center:update:variable:admin"
          ]
        }
      }
    }
  },
  "components": {}
}
