{
  "openapi": "3.0.0",
  "info": {
    "title": "Zoom Events API",
    "description": "Zoom Events API enables seamless integration, granting developers access to Zoom's data. Empower your apps with private services or public offerings on the [Zoom App Marketplace](https://marketplace.zoom.us/). Dive into [OAuth documentation](https://developers.zoom.us/docs/zoom-rooms/oauth/) for credential acquisition and app creation.",
    "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
    "contact": {
      "name": "Zoom Developers",
      "url": "https://developer.zoom.us/"
    },
    "version": "2"
  },
  "servers": [
    {
      "url": "https://api.zoom.us/v2"
    }
  ],
  "paths": {
    "/zoom_events/events/{eventId}/attendee_action": {
      "get": {
        "tags": [
          "Attendee Actions"
        ],
        "summary": "List Event Attendee Actions",
        "description": "Retrieves the attendee actions performed by host for an event.\n\n**Scopes:** `zoom_events_attendee_actions:read`,`zoom_events_attendee_actions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_attendee_actions`,`zoom_events:read:list_attendee_actions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "ListEventAttendeeActions",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_attendee_actions:read",
              "zoom_events_attendee_actions:read:admin",
              "zoom_events:read:list_attendee_actions",
              "zoom_events:read:list_attendee_actions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_attendee_actions:read",
            "zoom_events_attendee_actions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_attendee_actions",
            "zoom_events:read:list_attendee_actions:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Attendee Actions"
        ],
        "summary": "Update Event Attendee Actions",
        "description": "Retrieves attendee onsite action for an event. You can perform actions such as onsite check-in for a single attendee or up to 300 attendees in a batch operation. In the case of a batch operation, the API response can be partial success.  Any errors are returned in the **errors** object.\n\n**Scopes:** `zoom_events_attendee_actions:write`,`zoom_events_attendee_actions:write:admin`\n\n**Granular Scopes:** `zoom_events:update:batch_attendee_actions`,`zoom_events:update:batch[...]",
        "operationId": "UpdateEventAttendeeActions",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_attendee_actions:write",
              "zoom_events_attendee_actions:write:admin",
              "zoom_events:update:batch_attendee_actions",
              "zoom_events:update:batch_attendee_actions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_attendee_actions:write",
            "zoom_events_attendee_actions:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:batch_attendee_actions",
            "zoom_events:update:batch_attendee_actions:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions/{sessionId}/attendee_action": {
      "get": {
        "tags": [
          "Attendee Actions"
        ],
        "summary": "List Session Attendee Actions",
        "description": "Retrieves the attendee actions performed by host for an event session.\n\n**Scopes:** `zoom_events_attendee_actions:read`,`zoom_events_attendee_actions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_session_attendee_actions`,`zoom_events:read:list_session_attendee_actions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "ListSessionAttendeeActions",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_attendee_actions:read",
              "zoom_events_attendee_actions:read:admin",
              "zoom_events:read:list_session_attendee_actions",
              "zoom_events:read:list_session_attendee_actions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_attendee_actions:read",
            "zoom_events_attendee_actions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_session_attendee_actions",
            "zoom_events:read:list_session_attendee_actions:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Attendee Actions"
        ],
        "summary": "Update Session Attendee Actions",
        "description": "Use this API to perform attendee onsite action for an event session. You can perform actions such as onsite check-in for a single attendee or up to 300 attendees in a batch operation.In the case of a batch operation, the API response can be partial success.  Any errors are returned in the **errors** object.\n\n**Scopes:** `zoom_events_attendee_actions:write`,`zoom_events_attendee_actions:write:admin`\n\n**Granular Scopes:** `zoom_events:update:batch_session_attendee_actio[...]",
        "operationId": "UpdateSessionAttendeeActions",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_attendee_actions:write",
              "zoom_events_attendee_actions:write:admin",
              "zoom_events:update:batch_session_attendee_actions",
              "zoom_events:update:batch_session_attendee_actions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_attendee_actions:write",
            "zoom_events_attendee_actions:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:batch_session_attendee_actions",
            "zoom_events:update:batch_session_attendee_actions:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/coeditors": {
      "get": {
        "tags": [
          "Co Editors"
        ],
        "summary": "  List coeditors",
        "description": "Retrieves the list of co-editors and their edit permissions for an event.   Co-editors can make changes to the event details. Co-editors have view permission to all sections of the event.\n\n**Scopes:** `zoom_events_coeditors:read`,`zoom_events_coeditors:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_coeditors`,`zoom_events:read:list_coeditors:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getCoEditors",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_coeditors:read",
              "zoom_events_coeditors:read:admin",
              "zoom_events:read:list_coeditors",
              "zoom_events:read:list_coeditors:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_coeditors:read",
            "zoom_events_coeditors:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_coeditors",
            "zoom_events:read:list_coeditors:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/access_links": {
      "get": {
        "tags": [
          "Event Access"
        ],
        "summary": "List event access links",
        "description": "Retrieves a list of all the event's access links associated with the event.\n\n**Scopes:** `zoom_events_access_links:read:admin`,`zoom_events_access_links:read`\n\n**Granular Scopes:** `zoom_events:read:list_access_links`,`zoom_events:read:list_access_links:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEventAccessLinks",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_access_links:read:admin",
              "zoom_events_access_links:read",
              "zoom_events:read:list_access_links",
              "zoom_events:read:list_access_links:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_access_links:read:admin",
            "zoom_events_access_links:read"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_access_links",
            "zoom_events:read:list_access_links:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Event Access"
        ],
        "summary": "Create event access link",
        "description": "Create an access link for an event.\n\n**Scopes:** `zoom_events_access_links:write`,`zoom_events_access_links:write:admin`\n\n**Granular Scopes:** `zoom_events:write:access_links`,`zoom_events:write:access_links:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createEventAccessLink",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_access_links:write",
              "zoom_events_access_links:write:admin",
              "zoom_events:write:access_links",
              "zoom_events:write:access_links:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_access_links:write",
            "zoom_events_access_links:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:access_links",
            "zoom_events:write:access_links:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/access_links/{accessLinkId}": {
      "get": {
        "tags": [
          "Event Access"
        ],
        "summary": "Get event access link",
        "description": "Get event access link information.\n\n**Scopes:** `zoom_events_access_links:read`,`zoom_events_access_links:read:admin`\n\n**Granular Scopes:** `zoom_events:read:access_links`,`zoom_events:read:access_links:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "GetEventAccessLink",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_access_links:read",
              "zoom_events_access_links:read:admin",
              "zoom_events:read:access_links",
              "zoom_events:read:access_links:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_access_links:read",
            "zoom_events_access_links:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:access_links",
            "zoom_events:read:access_links:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Event Access"
        ],
        "summary": "Delete event access link",
        "description": "Deletes an event access link.\n\n**Scopes:** `zoom_events_access_links:write`,`zoom_events_access_links:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:access_links`,`zoom_events:delete:access_links:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteEventAccessLink",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_access_links:write",
              "zoom_events_access_links:write:admin",
              "zoom_events:delete:access_links",
              "zoom_events:delete:access_links:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_access_links:write",
            "zoom_events_access_links:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:access_links",
            "zoom_events:delete:access_links:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Event Access"
        ],
        "summary": "Update Event Access",
        "description": "Updates the event access for an event ID.\n\n**Scopes:** `zoom_events_access_links:write`,`zoom_events_access_links:write:admin`\n\n**Granular Scopes:** `zoom_events:update:access_links`,`zoom_events:update:access_links:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateEventAccess",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_access_links:write",
              "zoom_events_access_links:write:admin",
              "zoom_events:update:access_links",
              "zoom_events:update:access_links:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_access_links:write",
            "zoom_events_access_links:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:access_links",
            "zoom_events:update:access_links:admin"
          ]
        }
      }
    },
    "/zoom_events/events": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "List events",
        "description": "Retrieves all events associated with the user.\n\n\n\n**Scopes:** `zoom_events_basic:read`,`zoom_events_basic:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_events`,`zoom_events:read:list_events:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEvents",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_basic:read",
              "zoom_events_basic:read:admin",
              "zoom_events:read:list_events",
              "zoom_events:read:list_events:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_basic:read",
            "zoom_events_basic:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_events",
            "zoom_events:read:list_events:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Events"
        ],
        "summary": "Create an event",
        "description": "Creates an event.\n\n**Scopes:** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**Granular Scopes:** `zoom_events:write:event`,`zoom_events:write:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createEvent",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_basic:write",
              "zoom_events_basic:write:admin",
              "zoom_events:write:event",
              "zoom_events:write:event:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_basic:write",
            "zoom_events_basic:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:event",
            "zoom_events:write:event:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get an event",
        "description": "Returns information on a specified event.\n\n \n\n**Scopes:** `zoom_events_basic:read`,`zoom_events_basic:read:admin`\n\n**Granular Scopes:** `zoom_events:read:event`,`zoom_events:read:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEventInfo",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_basic:read",
              "zoom_events_basic:read:admin",
              "zoom_events:read:event",
              "zoom_events:read:event:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_basic:read",
            "zoom_events_basic:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:event",
            "zoom_events:read:event:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Events"
        ],
        "summary": "Delete an event",
        "description": "Delete a draft event.\n\n**Scopes:** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:event`,`zoom_events:delete:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteEvent",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_basic:write",
              "zoom_events_basic:write:admin",
              "zoom_events:delete:event",
              "zoom_events:delete:event:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_basic:write",
            "zoom_events_basic:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:event",
            "zoom_events:delete:event:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Events"
        ],
        "summary": "Update an event",
        "description": "Updates an event.\n\n**Scopes:** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**Granular Scopes:** `zoom_events:update:event`,`zoom_events:update:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateEvent",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_basic:write",
              "zoom_events_basic:write:admin",
              "zoom_events:update:event",
              "zoom_events:update:event:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_basic:write",
            "zoom_events_basic:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:event",
            "zoom_events:update:event:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/event_actions": {
      "post": {
        "tags": [
          "Events"
        ],
        "summary": "Event Actions",
        "description": "Updates the event actions that the host performs for an event.\n\n**Scopes:** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**Granular Scopes:** `zoom_events:write:event`,`zoom_events:write:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "EventActions",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_basic:write",
              "zoom_events_basic:write:admin",
              "zoom_events:write:event",
              "zoom_events:write:event:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_basic:write",
            "zoom_events_basic:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:event",
            "zoom_events:write:event:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/exhibitors": {
      "get": {
        "tags": [
          "Exhibitors"
        ],
        "summary": "List Exhibitors",
        "description": "Lists all exhibitors associated with an event.\n\n\n\n**Scopes:** `zoom_events_exhibitors:read:admin`,`zoom_events_exhibitors:read`\n\n**Granular Scopes:** `zoom_events:read:list_exhibitors`,`zoom_events:read:list_exhibitors:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getExhibitors",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_exhibitors:read:admin",
              "zoom_events_exhibitors:read",
              "zoom_events:read:list_exhibitors",
              "zoom_events:read:list_exhibitors:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_exhibitors:read:admin",
            "zoom_events_exhibitors:read"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_exhibitors",
            "zoom_events:read:list_exhibitors:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Exhibitors"
        ],
        "summary": "Create a Exhibitor",
        "description": "Creates an exhibitor for a multi-session and conference type event.\n\n**Scopes:** `zoom_events_exhibitors:write`,`zoom_events_exhibitors:write:admin`\n\n**Granular Scopes:** `zoom_events:write:exhibitor`,`zoom_events:write:exhibitor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createExhibitor",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_exhibitors:write",
              "zoom_events_exhibitors:write:admin",
              "zoom_events:write:exhibitor",
              "zoom_events:write:exhibitor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_exhibitors:write",
            "zoom_events_exhibitors:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:exhibitor",
            "zoom_events:write:exhibitor:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/exhibitors/{exhibitorId}": {
      "get": {
        "tags": [
          "Exhibitors"
        ],
        "summary": "Get an Exhibitor",
        "description": "Returns the exhibitor information of a specified event.\n\n \n\n**Scopes:** `zoom_events_exhibitors:read`,`zoom_events_exhibitors:read:admin`\n\n**Granular Scopes:** `zoom_events:read:exhibitor`,`zoom_events:read:exhibitor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getExhibitorInfo",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_exhibitors:read",
              "zoom_events_exhibitors:read:admin",
              "zoom_events:read:exhibitor",
              "zoom_events:read:exhibitor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_exhibitors:read",
            "zoom_events_exhibitors:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:exhibitor",
            "zoom_events:read:exhibitor:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Exhibitors"
        ],
        "summary": "Delete an exhibitor",
        "description": "Deletes an exhibitor.\n\n\n\n**Scopes:** `zoom_events_exhibitors:write`,`zoom_events_exhibitors:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:exhibitor`,`zoom_events:delete:exhibitor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteExhibitor",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_exhibitors:write",
              "zoom_events_exhibitors:write:admin",
              "zoom_events:delete:exhibitor",
              "zoom_events:delete:exhibitor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_exhibitors:write",
            "zoom_events_exhibitors:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:exhibitor",
            "zoom_events:delete:exhibitor:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Exhibitors"
        ],
        "summary": "Update exhibitor for an event",
        "description": "Updates the exhibitor for an event ID. This operation is only allowed for multi session event type.\n\n**Scopes:** `zoom_events_exhibitors:write`,`zoom_events_exhibitors:write:admin`\n\n**Granular Scopes:** `zoom_events:update:exhibitor`,`zoom_events:update:exhibitor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateExhibitor",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_exhibitors:write",
              "zoom_events_exhibitors:write:admin",
              "zoom_events:update:exhibitor",
              "zoom_events:update:exhibitor:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_exhibitors:write",
            "zoom_events_exhibitors:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:exhibitor",
            "zoom_events:update:exhibitor:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sponsor_tiers": {
      "get": {
        "tags": [
          "Exhibitors"
        ],
        "summary": "List Sponsor Tiers",
        "description": "Lists all sponsor tiers associated with an event.\n\n\n**Scopes:** `zoom_events_exhibitors:read:admin`,`zoom_events_exhibitors:read`\n\n**Granular Scopes:** `zoom_events:read:list_sponsor_tiers`,`zoom_events:read:list_sponsor_tiers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "ListSponsorTiers",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_exhibitors:read:admin",
              "zoom_events_exhibitors:read",
              "zoom_events:read:list_sponsor_tiers",
              "zoom_events:read:list_sponsor_tiers:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_exhibitors:read:admin",
            "zoom_events_exhibitors:read"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_sponsor_tiers",
            "zoom_events:read:list_sponsor_tiers:admin"
          ]
        }
      }
    },
    "/zoom_events/hubs": {
      "get": {
        "tags": [
          "Hubs"
        ],
        "summary": "List hubs",
        "description": "Retrieve a list of event hubs.\n\n**Scopes:** `zoom_events_hubs:read`,`zoom_events_hubs:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_hubs`,`zoom_events:read:list_hubs:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getHubList",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_hubs:read",
              "zoom_events_hubs:read:admin",
              "zoom_events:read:list_hubs",
              "zoom_events:read:list_hubs:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_hubs:read",
            "zoom_events_hubs:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_hubs",
            "zoom_events:read:list_hubs:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/registrants": {
      "get": {
        "tags": [
          "Registrants"
        ],
        "summary": "List registrants",
        "description": "Retrieves event registrants.\n\n**Scopes:** `zoom_events_registrants:read`,`zoom_events_registrants:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_registrants`,`zoom_events:read:list_registrants:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getRegistrants",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_registrants:read",
              "zoom_events_registrants:read:admin",
              "zoom_events:read:list_registrants",
              "zoom_events:read:list_registrants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_registrants:read",
            "zoom_events_registrants:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_registrants",
            "zoom_events:read:list_registrants:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions/{sessionId}/attendees": {
      "get": {
        "tags": [
          "Registrants"
        ],
        "summary": "List session attendees",
        "description": "Retrieves session attendees.\n\n**Scopes:** `zoom_events_registrants:read`,`zoom_events_registrants:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_session_attendees`,`zoom_events:read:list_session_attendees:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSessionAttendeeList",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_registrants:read",
              "zoom_events_registrants:read:admin",
              "zoom_events:read:list_session_attendees",
              "zoom_events:read:list_session_attendees:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_registrants:read",
            "zoom_events_registrants:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_session_attendees",
            "zoom_events:read:list_session_attendees:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/reports/chat_transcripts": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get chat transcripts report",
        "description": "Retrieves the chat transcripts report for an event.  \n At this present time, this API returns data only for users who enabled [meeting and webinar cloud archiving feature](https://support.zoom.us/hc/en-us/articles/360061037572-Configuring-archival-settings-for-meetings-and-webinars).  \n Whether users can download in-meeting, private 1:1 and private group chats depends on the meeting and webinar cloud archiving feature.  \n Below chat types data is returned based on the [...]",
        "operationId": "ChatTranscriptsReport",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_reports:read",
              "zoom_events_reports:read:admin",
              "zoom_events:read:chat_transcripts",
              "zoom_events:read:chat_transcripts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_reports:read",
            "zoom_events_reports:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:chat_transcripts",
            "zoom_events:read:chat_transcripts:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/reports/event_attendance": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Event Attendance Report",
        "description": "Retrieves event attendance report.\n\n**Scopes:** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**Granular Scopes:** `zoom_events:read:event_attendance`,`zoom_events:read:event_attendance:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "EventAttendanceReport",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_reports:read",
              "zoom_events_reports:read:admin",
              "zoom_events:read:event_attendance",
              "zoom_events:read:event_attendance:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_reports:read",
            "zoom_events_reports:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:event_attendance",
            "zoom_events:read:event_attendance:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/reports/survey": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Event Survey Report",
        "description": "Retrieves event and session survey information.\n\n**Scopes:** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_session_surveys`,`zoom_events:read:list_session_surveys:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "EventSurveyReportApi",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_reports:read",
              "zoom_events_reports:read:admin",
              "zoom_events:read:list_session_surveys",
              "zoom_events:read:list_session_surveys:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_reports:read",
            "zoom_events_reports:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_session_surveys",
            "zoom_events:read:list_session_surveys:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/reports/ticket_registration": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Event Registrations Report",
        "description": "Retrieves event ticket registrations.\n\n**Scopes:** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**Granular Scopes:** `zoom_events:read:event_registration`,`zoom_events:read:event_registration:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "EventRegistrationsReport",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_reports:read",
              "zoom_events_reports:read:admin",
              "zoom_events:read:event_registration",
              "zoom_events:read:event_registration:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_reports:read",
            "zoom_events_reports:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:event_registration",
            "zoom_events:read:event_registration:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "List sessions",
        "description": "Retrieves the sessions in an event.\n\n**Scopes:** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_sessions`,`zoom_events:read:list_sessions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEventSessionList",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:read",
              "zoom_events_sessions:read:admin",
              "zoom_events:read:list_sessions",
              "zoom_events:read:list_sessions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:read",
            "zoom_events_sessions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_sessions",
            "zoom_events:read:list_sessions:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Sessions"
        ],
        "summary": "Create a session",
        "description": "Creates a session. This operation is not available for single session event type.\n\n**Scopes:** `zoom_events_sessions:write:admin`,`zoom_events_sessions:write`\n\n**Granular Scopes:** `zoom_events:write:session`,`zoom_events:write:session:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createEventSession",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:write:admin",
              "zoom_events_sessions:write",
              "zoom_events:write:session",
              "zoom_events:write:session:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:write:admin",
            "zoom_events_sessions:write"
          ],
          "x-granular-scopes": [
            "zoom_events:write:session",
            "zoom_events:write:session:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions/{sessionId}": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "Get the session information",
        "description": "Returns the session information.\n\n\n\n**Scopes:** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:session`,`zoom_events:read:session:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEventSessionInfo",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:read",
              "zoom_events_sessions:read:admin",
              "zoom_events:read:session",
              "zoom_events:read:session:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:read",
            "zoom_events_sessions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:session",
            "zoom_events:read:session:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Sessions"
        ],
        "summary": "Delete a session",
        "description": "Deletes a session. This API is not allowed for single session event type.\n\n**Scopes:** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:session`,`zoom_events:delete:session:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteEventSession",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:write",
              "zoom_events_sessions:write:admin",
              "zoom_events:delete:session",
              "zoom_events:delete:session:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:write",
            "zoom_events_sessions:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:session",
            "zoom_events:delete:session:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Sessions"
        ],
        "summary": "Update a session",
        "description": "Updates an existing session in an event. \n\n**Scopes:** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**Granular Scopes:** `zoom_events:update:session`,`zoom_events:update:session:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateEventSession",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:write",
              "zoom_events_sessions:write:admin",
              "zoom_events:update:session",
              "zoom_events:update:session:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:write",
            "zoom_events_sessions:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:session",
            "zoom_events:update:session:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions/{sessionId}/interpreters": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "List session interpreters",
        "description": "Retrieves interpreters in a session.\n\n**Scopes:** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_session_interpreters`,`zoom_events:read:list_session_interpreters:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSessionInterpreterList",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:read",
              "zoom_events_sessions:read:admin",
              "zoom_events:read:list_session_interpreters",
              "zoom_events:read:list_session_interpreters:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:read",
            "zoom_events_sessions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_session_interpreters",
            "zoom_events:read:list_session_interpreters:admin"
          ]
        }
      },
      "put": {
        "tags": [
          "Sessions"
        ],
        "summary": "Create or update session interpreters.",
        "description": "Creates or update the list of interpreters for the session.\n\n**Scopes:** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**Granular Scopes:** `zoom_events:update:session_interpreter`,`zoom_events:update:session_interpreter:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateSessionInterpreters",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:write",
              "zoom_events_sessions:write:admin",
              "zoom_events:update:session_interpreter",
              "zoom_events:update:session_interpreter:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:write",
            "zoom_events_sessions:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:session_interpreter",
            "zoom_events:update:session_interpreter:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions/{sessionId}/join_token": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "Get ticket session join token by Event ID and Session ID",
        "description": "Retrieves the join token to join an event session.\n\n\n\n**Scopes:** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:session_token`,`zoom_events:read:session_token:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSessionJoinToken",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:read",
              "zoom_events_sessions:read:admin",
              "zoom_events:read:session_token",
              "zoom_events:read:session_token:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:read",
            "zoom_events_sessions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:session_token",
            "zoom_events:read:session_token:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/sessions/{sessionId}/polls": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "List session polls",
        "description": "List all the polls of a session.\n\n\n\n**Scopes:** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_session_polls`,`zoom_events:read:list_session_polls:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSessionPolls",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:read",
              "zoom_events_sessions:read:admin",
              "zoom_events:read:list_session_polls",
              "zoom_events:read:list_session_polls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:read",
            "zoom_events_sessions:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_session_polls",
            "zoom_events:read:list_session_polls:admin"
          ]
        }
      },
      "put": {
        "tags": [
          "Sessions"
        ],
        "summary": "Create or update session polls.",
        "description": "Create or update the list of polls for the session.\n\n**Scopes:** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**Granular Scopes:** `zoom_events:update:session_poll`,`zoom_events:update:session_poll:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateSessionPolls",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_sessions:write",
              "zoom_events_sessions:write:admin",
              "zoom_events:update:session_poll",
              "zoom_events:update:session_poll:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_sessions:write",
            "zoom_events_sessions:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:session_poll",
            "zoom_events:update:session_poll:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/speakers": {
      "get": {
        "tags": [
          "Speakers"
        ],
        "summary": "List speakers",
        "description": "Retrieves a list of speakers for an event.\n\n**Scopes:** `zoom_events_speakers:read`,`zoom_events_speakers:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_speakers`,`zoom_events:read:list_speakers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSpeakers",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_speakers:read",
              "zoom_events_speakers:read:admin",
              "zoom_events:read:list_speakers",
              "zoom_events:read:list_speakers:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_speakers:read",
            "zoom_events_speakers:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_speakers",
            "zoom_events:read:list_speakers:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Speakers"
        ],
        "summary": "Create a speaker",
        "description": "Creates a speaker for an event.\n\n**Scopes:** `zoom_events_speakers:write`,`zoom_events_speakers:write:admin`\n\n**Granular Scopes:** `zoom_events:write:speaker`,`zoom_events:write:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createSpeaker",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_speakers:write",
              "zoom_events_speakers:write:admin",
              "zoom_events:write:speaker",
              "zoom_events:write:speaker:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_speakers:write",
            "zoom_events_speakers:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:speaker",
            "zoom_events:write:speaker:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/speakers/{speakerId}": {
      "get": {
        "tags": [
          "Speakers"
        ],
        "summary": "Get a speaker",
        "description": "Returns information on a specific speaker.\n\n\n\n**Scopes:** `zoom_events_speakers:read`,`zoom_events_speakers:read:admin`\n\n**Granular Scopes:** `zoom_events:read:speaker`,`zoom_events:read:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getSpeaker",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_speakers:read",
              "zoom_events_speakers:read:admin",
              "zoom_events:read:speaker",
              "zoom_events:read:speaker:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_speakers:read",
            "zoom_events_speakers:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:speaker",
            "zoom_events:read:speaker:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Speakers"
        ],
        "summary": "Delete a speaker",
        "description": "Deletes a speaker.\n\n\n\n**Scopes:** `zoom_events_speakers:write`,`zoom_events_speakers:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:speaker`,`zoom_events:delete:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteSpeaker",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_speakers:write",
              "zoom_events_speakers:write:admin",
              "zoom_events:delete:speaker",
              "zoom_events:delete:speaker:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_speakers:write",
            "zoom_events_speakers:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:speaker",
            "zoom_events:delete:speaker:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Speakers"
        ],
        "summary": "Update a speaker",
        "description": "Updates the speaker information.\n\n**Scopes:** `zoom_events_speakers:write`,`zoom_events_speakers:write:admin`\n\n**Granular Scopes:** `zoom_events:update:speaker`,`zoom_events:update:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateSpeaker",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_speakers:write",
              "zoom_events_speakers:write:admin",
              "zoom_events:update:speaker",
              "zoom_events:update:speaker:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_speakers:write",
            "zoom_events_speakers:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:speaker",
            "zoom_events:update:speaker:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/questions": {
      "get": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "List registration questions for an event",
        "description": "List registration questions and fields that are to be answered by users while registering for an event. These questions are setup during the event level.\n\n**Scopes:** `zoom_events_ticket_types:read`,`zoom_events_ticket_types:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_registration_questions`,`zoom_events:read:list_registration_questions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getRegistrationQuestionsForEvent",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:read",
              "zoom_events_ticket_types:read:admin",
              "zoom_events:read:list_registration_questions",
              "zoom_events:read:list_registration_questions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:read",
            "zoom_events_ticket_types:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_registration_questions",
            "zoom_events:read:list_registration_questions:admin"
          ]
        }
      },
      "put": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "Update registration questions for an event",
        "description": "Updates registration questions and fields that are to be answered by users while registering for an event. These questions are setup at event level.\n\n**Scopes:** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**Granular Scopes:** `zoom_events:update:registraion_question`,`zoom_events:update:registraion_question:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateRegistrationQuestionsForEvent",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:write",
              "zoom_events_ticket_types:write:admin",
              "zoom_events:update:registraion_question",
              "zoom_events:update:registraion_question:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:write",
            "zoom_events_ticket_types:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:registraion_question",
            "zoom_events:update:registraion_question:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/ticket_types": {
      "get": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "List ticket types",
        "description": "Lists all ticket types associated with an event.\n\n\n\n**Scopes:** `zoom_events_ticket_types:read`,`zoom_events_ticket_types:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_ticket_types`,`zoom_events:read:list_ticket_types:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getEventTicketTypes",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:read",
              "zoom_events_ticket_types:read:admin",
              "zoom_events:read:list_ticket_types",
              "zoom_events:read:list_ticket_types:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:read",
            "zoom_events_ticket_types:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_ticket_types",
            "zoom_events:read:list_ticket_types:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "Create an event ticket type",
        "description": "Creates a ticket type for the event ID. This API is not allowed for single session and recurring event type.\n\n**Scopes:** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**Granular Scopes:** `zoom_events:write:ticket_type`,`zoom_events:write:ticket_type:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "createTicketType",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:write",
              "zoom_events_ticket_types:write:admin",
              "zoom_events:write:ticket_type",
              "zoom_events:write:ticket_type:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:write",
            "zoom_events_ticket_types:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:ticket_type",
            "zoom_events:write:ticket_type:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/ticket_types/{ticketTypeId}": {
      "delete": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "Delete a ticket type",
        "description": "Deletes a ticket type of an event. This API is not allowed for single session event type.\n\n**Scopes:** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:ticket_type`,`zoom_events:delete:ticket_type:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteEventTicketType",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:write",
              "zoom_events_ticket_types:write:admin",
              "zoom_events:delete:ticket_type",
              "zoom_events:delete:ticket_type:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:write",
            "zoom_events_ticket_types:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:ticket_type",
            "zoom_events:delete:ticket_type:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "Update ticket type for an event",
        "description": "Updates the ticket type for an event ID. This API is not allowed for single session event type.\n\n**Scopes:** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**Granular Scopes:** `zoom_events:update:ticket_type`,`zoom_events:update:ticket_type:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "updateTicketType",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:write",
              "zoom_events_ticket_types:write:admin",
              "zoom_events:update:ticket_type",
              "zoom_events:update:ticket_type:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:write",
            "zoom_events_ticket_types:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:ticket_type",
            "zoom_events:update:ticket_type:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/ticket_types/{ticketTypeId}/questions": {
      "get": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "List registration questions for ticket type",
        "description": "List registration questions and fields that are to be answered by users while registering for an event. These questions are setup at ticket_type level.\n\n**Scopes:** `zoom_events_ticket_types:read`,`zoom_events_ticket_types:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_registration_questions`,`zoom_events:read:list_registration_questions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getRegistrationQuestionsForTicketType",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:read",
              "zoom_events_ticket_types:read:admin",
              "zoom_events:read:list_registration_questions",
              "zoom_events:read:list_registration_questions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:read",
            "zoom_events_ticket_types:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_registration_questions",
            "zoom_events:read:list_registration_questions:admin"
          ]
        }
      },
      "put": {
        "tags": [
          "Ticket Types"
        ],
        "summary": "Update registration questions for ticket type",
        "description": "Updates registration questions and fields that are to be answered by users while registering for an event. These questions are setup at ticket_type level. This API is not allowed for single session event type.\n\n**Scopes:** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**Granular Scopes:** `zoom_events:update:registraion_question`,`zoom_events:update:registraion_question:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refe[...]",
        "operationId": "updateRegistrationQuestionsForTicketType",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_ticket_types:write",
              "zoom_events_ticket_types:write:admin",
              "zoom_events:update:registraion_question",
              "zoom_events:update:registraion_question:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_ticket_types:write",
            "zoom_events_ticket_types:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:update:registraion_question",
            "zoom_events:update:registraion_question:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/tickets": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "List tickets",
        "description": "Retrieves the ticket information of an event.\n\n**Scopes:** `zoom_events_tickets:read`,`zoom_events_tickets:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_tickets`,`zoom_events:read:list_tickets:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getTickets",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_tickets:read",
              "zoom_events_tickets:read:admin",
              "zoom_events:read:list_tickets",
              "zoom_events:read:list_tickets:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_tickets:read",
            "zoom_events_tickets:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_tickets",
            "zoom_events:read:list_tickets:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Tickets"
        ],
        "summary": "Create tickets",
        "description": "Create tickets for an event. You can add a single ticket or up to 30 tickets in a batch operation. Please note that this request uses the [`pre-registration`](https://support.zoom.us/hc/en-us/articles/13475985512973-Pre-registering-Zoom-Events-guests) flow. \n\n**Scopes:** `zoom_events_tickets:write`,`zoom_events_tickets:write:admin`\n\n**Granular Scopes:** `zoom_events:write:ticket`,`zoom_events:write:ticket:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs[...]",
        "operationId": "createTickets",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_tickets:write",
              "zoom_events_tickets:write:admin",
              "zoom_events:write:ticket",
              "zoom_events:write:ticket:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_tickets:write",
            "zoom_events_tickets:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:ticket",
            "zoom_events:write:ticket:admin"
          ]
        }
      }
    },
    "/zoom_events/events/{eventId}/tickets/{ticketId}": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Get a ticket",
        "description": "Retrieves information on a specific ticket.\n\n**Scopes:** `zoom_events_tickets:read`,`zoom_events_tickets:read:admin`\n\n**Granular Scopes:** `zoom_events:read:ticket`,`zoom_events:read:ticket:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getTicketDetails",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_tickets:read",
              "zoom_events_tickets:read:admin",
              "zoom_events:read:ticket",
              "zoom_events:read:ticket:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_tickets:read",
            "zoom_events_tickets:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:ticket",
            "zoom_events:read:ticket:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Tickets"
        ],
        "summary": "Delete a ticket",
        "description": "Deletes a ticket.\n\n**Scopes:** `zoom_events_tickets:write`,`zoom_events_tickets:write:admin`\n\n**Granular Scopes:** `zoom_events:delete:ticket`,`zoom_events:delete:ticket:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "deleteTicket",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_tickets:write",
              "zoom_events_tickets:write:admin",
              "zoom_events:delete:ticket",
              "zoom_events:delete:ticket:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_tickets:write",
            "zoom_events_tickets:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:delete:ticket",
            "zoom_events:delete:ticket:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Tickets"
        ],
        "summary": "Update ticket",
        "description": "Updates ticket questions for the given ticket ID and event ID.\n\n**Scopes:** `zoom_events_tickets:write`,`zoom_events_tickets:write:admin`\n\n**Granular Scopes:** `zoom_events:write:ticket`,`zoom_events:write:ticket:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "Updateticket",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_tickets:write",
              "zoom_events_tickets:write:admin",
              "zoom_events:write:ticket",
              "zoom_events:write:ticket:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "july-2024-zoap-gateway",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_tickets:write",
            "zoom_events_tickets:write:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:write:ticket",
            "zoom_events:write:ticket:admin"
          ]
        }
      }
    },
    "/zoom_events/hubs/{hubId}/vod_channels": {
      "get": {
        "tags": [
          "Video On-Demand"
        ],
        "summary": "List channels",
        "description": "Retrieves the channel information for a hub.\n\n**Scopes:** `zoom_events_vod_channels:read`,`zoom_events_vod_channels:read:admin`\n\n**Granular Scopes:** `zoom_events:read:list_all_vod_channels`,`zoom_events:read:list_all_vod_channels:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "getVODChannels",
        "security": [
          {
            "openapi_oauth": [
              "zoom_events_vod_channels:read",
              "zoom_events_vod_channels:read:admin",
              "zoom_events:read:list_all_vod_channels",
              "zoom_events:read:list_all_vod_channels:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-fixVersion": "May-2024",
          "x-permissions": [],
          "x-macro-scopes": [
            "zoom_events_vod_channels:read",
            "zoom_events_vod_channels:read:admin"
          ],
          "x-granular-scopes": [
            "zoom_events:read:list_all_vod_channels",
            "zoom_events:read:list_all_vod_channels:admin"
          ]
        }
      }
    }
  },
  "components": {}
}
