{
 "openapi": "3.0.0",
 "info": {
  "title": "Zoom Marketplace API",
  "description": "Marketplace",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/app/notifications": {
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Send app notifications",
    "description": "Send app notifications to the Zoom \"Activity Center\". (Note: This API only supports OAuth 2.0.)\n\n**Scopes:** `app:notification:read`,`app:notification:write`\n\n**Granular Scopes:** `marketplace:write:notifications`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Sendappnotifications",
    "security": [
     {
      "openapi_oauth": [
       "app:notification:read",
       "app:notification:write",
       "marketplace:write:notifications"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "Web-2024-Jun",
     "x-permissions": [],
     "x-macro-scopes": [
      "app:notification:read",
      "app:notification:write"
     ],
     "x-granular-scopes": [
      "marketplace:write:notifications"
     ]
    }
   }
  },
  "/marketplace/apps": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "List apps",
    "description": "Use this API to list all active and past app requests, or list all public and private apps. \n\n\n\n**Scopes:** `marketplace_app:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "ListApps",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "InitFixVersion",
     "x-macro-scopes": [
      "marketplace_app:read:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get information about an app",
    "description": "Use this API to get app information. \n\n\n\n**Scopes:** `marketplace_app:read`,`marketplace_app:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getAppInfo",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read",
       "marketplace_app:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "InitFixVersion",
     "x-macro-scopes": [
      "marketplace_app:read",
      "marketplace_app:read:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/requests": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get an app's user requests",
    "description": "Use this API to get an app's user requests and the status of their approval. \n\n\n\n**Scopes:** `marketplace_app:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getAppUserRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "InitFixVersion",
     "x-macro-scopes": [
      "marketplace_app:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Add app allow requests for users",
    "description": "Use this API to add app allow requests for all users, groups of users, or specific users. \n\n \n\n**Scopes:** `marketplace_app:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "AddAppAllowRequestsForUsers",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "InitFixVersion",
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "App"
    ],
    "summary": "Update app's request status",
    "description": "Use this API to update an app's request status or update app status. Administrators can only agree to user-level apps.\n\n \n\n**Scopes:** `marketplace_app:write:admin`\n\n**Granular Scopes:** `marketplace:update:app_request:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateAppRequestStatus",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin",
       "marketplace:update:app_request:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "Marketplace-2024-Jun",
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:update:app_request:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/webhook_logs": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get webhook logs",
    "description": "Get users' webhook call logs and query records from the past 7 days. \n\n\n\n**Scopes:** `marketplace_app:read:admin`,`marketplace_app:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getWebhookLogs",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin",
       "marketplace_app:read"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "Marketplace-2023-Jun",
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read:admin",
      "marketplace_app:read"
     ]
    }
   }
  },
  "/marketplace/monetization/entitlements": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get app user entitlements",
    "description": "Get the app user's entitlements information.\n\n**Scopes:** `marketplace_entitlement:read:admin`,`marketplace_entitlement:read`\n\n**Granular Scopes:** `marketplace:read:list_user_entitlements`,`marketplace:read:list_user_entitlements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "getAppUserEntitlementRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_entitlement:read:admin",
       "marketplace_entitlement:read",
       "marketplace:read:list_user_entitlements",
       "marketplace:read:list_user_entitlements:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "Marketplace-2024-Jun",
     "x-permissions": [
      "Marketplace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_entitlement:read:admin",
      "marketplace_entitlement:read"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_user_entitlements",
      "marketplace:read:list_user_entitlements:admin"
     ]
    }
   }
  },
  "/marketplace/users/{userId}/apps": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get a user's app requests",
    "description": "Use this API to get all of a user's app requests. \n\n\n\n**Scopes:** `marketplace_app:read`,`marketplace_app:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getUserAppRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read",
       "marketplace_app:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "InitFixVersion",
     "x-macro-scopes": [
      "marketplace_app:read",
      "marketplace_app:read:admin"
     ]
    }
   }
  },
  "/marketplace/users/{userId}/entitlements": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get a user's entitlements",
    "description": "Get a user's entitlements. \n\n\n\n**Scopes:** `marketplace_entitlement:read`,`marketplace_entitlement:read:admin`\n\n**Granular Scopes:** `marketplace:read:list_user_entitlements`,`marketplace:read:list_user_entitlements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getUserEntitlementRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_entitlement:read",
       "marketplace_entitlement:read:admin",
       "marketplace:read:list_user_entitlements",
       "marketplace:read:list_user_entitlements:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "Marketplace-2024-Jun",
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_entitlement:read",
      "marketplace_entitlement:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_user_entitlements",
      "marketplace:read:list_user_entitlements:admin"
     ]
    }
   }
  },
  "/zoomapp/deeplink": {
   "post": {
    "tags": [
     "Apps"
    ],
    "summary": "Generate an app deeplink",
    "description": "Create an app deeplink. \n\n \n\n**Scopes:** `app:deeplink:write`,`app:deeplink:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "generateAppDeeplink",
    "security": [
     {
      "openapi_oauth": [
       "app:deeplink:write",
       "app:deeplink:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "InitFixVersion",
     "x-macro-scopes": [
      "app:deeplink:write",
      "app:deeplink:write:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "app:notification:read": "app:notification:read",
       "app:notification:write": "app:notification:write",
       "marketplace:write:notifications": "marketplace:write:notifications",
       "marketplace_app:read:admin": "marketplace_app:read:admin",
       "marketplace_app:read": "marketplace_app:read",
       "marketplace_app:write:admin": "marketplace_app:write:admin",
       "marketplace:update:app_request:admin": "marketplace:update:app_request:admin",
       "marketplace_entitlement:read:admin": "marketplace_entitlement:read:admin",
       "marketplace_entitlement:read": "marketplace_entitlement:read",
       "marketplace:read:list_user_entitlements": "marketplace:read:list_user_entitlements",
       "marketplace:read:list_user_entitlements:admin": "marketplace:read:list_user_entitlements:admin",
       "app:deeplink:write": "app:deeplink:write",
       "app:deeplink:write:admin": "app:deeplink:write:admin"
      }
     }
    }
   }
  }
 }
}