{
 "openapi": "3.0.0",
 "info": {
  "title": "Zoom Whiteboard API",
  "description": "The Zoom Whiteboard APIs allow you to manage your Zoom Whiteboard. For example, collaborative persistent whiteboard that allows participants to share and collaborate on a virtual whiteboard in real time The Zoom Whiteboard REST API for [Zoom Whiteboard](https://developers.zoom.us/docs/api/rest/whiteboard/) allows developers to interact with various Zoom features, including Zoom Whiteboard. Developers can create and manage whiteboards programmatically using these APIs.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/whiteboards/sessions": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "summary": "List whiteboards sessions",
    "description": "Lists archived sessions under current account.\n\n**Scopes:** `whiteboard_content:read:admin`,`whiteboard_content:read`\n\n**Granular Scopes:** `whiteboard:read:list_sessions`,`whiteboard:read:list_sessions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Createwhiteboardsarchivefiles",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_content:read:admin",
       "whiteboard_content:read",
       "whiteboard:read:list_sessions",
       "whiteboard:read:list_sessions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardContent:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_content:read:admin",
      "whiteboard_content:read"
     ],
     "x-granular-scopes": [
      "whiteboard:read:list_sessions",
      "whiteboard:read:list_sessions:admin"
     ]
    }
   }
  },
  "/whiteboards/sessions/activity/download/{path}": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "summary": "Download Whiteboards activity file",
    "description": "Use this API to download the Whiteboard archival file.\n\n**Scopes:** `whiteboard_content:read`,`whiteboard_content:read:admin`\n\n**Granular Scopes:** `whiteboard:read:archived_file`,`whiteboard:read:archived_file:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Downloadwhiteboardsactivityfile",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_content:read",
       "whiteboard_content:read:admin",
       "whiteboard:read:archived_file",
       "whiteboard:read:archived_file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardContent:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_content:read",
      "whiteboard_content:read:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:read:archived_file",
      "whiteboard:read:archived_file:admin"
     ]
    }
   }
  },
  "/whiteboards/sessions/{seesionId}": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "summary": "List whiteboard sessions activities",
    "description": "Lists a session's activity information.\n\n**Scopes:** `whiteboard_content:read`,`whiteboard_content:read:admin`\n\n**Granular Scopes:** `whiteboard:read:session`,`whiteboard:read:session:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Listwhiteboardsessionsarchivedfiles",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_content:read",
       "whiteboard_content:read:admin",
       "whiteboard:read:session",
       "whiteboard:read:session:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.15.0",
     "x-permissions": [
      "WhiteboardContent:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_content:read",
      "whiteboard_content:read:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:read:session",
      "whiteboard:read:session:admin"
     ]
    }
   }
  },
  "/whiteboards/{whiteboardId}/collaborator": {
   "get": {
    "tags": [
     "Collaborator"
    ],
    "summary": "Get collaborators of a whiteboard",
    "description": "Returns a list of a whiteboard collaborators. \n\n**Scopes:** `whiteboard_collaborator:read:admin`\n\n**Granular Scopes:** `whiteboard:read:list_collaborators:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GetAWhiteboardCollaborator",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_collaborator:read:admin",
       "whiteboard:read:list_collaborators:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_collaborator:read:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:read:list_collaborators:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Collaborator"
    ],
    "summary": "Share a whiteboard to new users or team chat channels.",
    "description": "Use this API to add collaborators to a whiteboard.\n\n**Scopes:** `whiteboard_collaborator:write:admin`\n\n**Granular Scopes:** `whiteboard:write:collaborator:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "AddAWhiteboardCollaborator",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_collaborator:write:admin",
       "whiteboard:write:collaborator:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Edit"
     ],
     "x-macro-scopes": [
      "whiteboard_collaborator:write:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:write:collaborator:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Collaborator"
    ],
    "summary": "Update whiteboard collaborators",
    "description": "Use this API to update whiteboard collaborators. \n\n\n\n**Scopes:** `whiteboard_collaborator:write:admin`\n\n**Granular Scopes:** `whiteboard:update:collaborator:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "UpdateAWhiteboardCollaborator",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_collaborator:write:admin",
       "whiteboard:update:collaborator:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Edit"
     ],
     "x-macro-scopes": [
      "whiteboard_collaborator:write:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:update:collaborator:admin"
     ]
    }
   }
  },
  "/whiteboards/{whiteboardId}/collaborator/{collaboratorId}": {
   "delete": {
    "tags": [
     "Collaborator"
    ],
    "summary": "Remove the collaborator from a whiteboard",
    "description": "Removes a collaborator from a whiteboard. \n\n\n\n**Scopes:** `whiteboard_collaborator:write:admin`\n\n**Granular Scopes:** `whiteboard:delete:collaborator:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "DeleteAWhiteboardCollaborator",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_collaborator:write:admin",
       "whiteboard:delete:collaborator:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Edit"
     ],
     "x-macro-scopes": [
      "whiteboard_collaborator:write:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:delete:collaborator:admin"
     ]
    }
   }
  },
  "/whiteboards": {
   "get": {
    "tags": [
     "Document"
    ],
    "summary": "List all whiteboards",
    "description": "Use this API to list whiteboards of current user (**Required Scopes**: `whiteboard:read`) or list all whiteboards under the account (**Required Scopes**: `whiteboard:read:admin`).\n\n**Note:** `user_id` can intake `Zoom user ID` or `email` which only applies when scope = `whiteboard:read:admin`. Otherwise, the `user_id` can only intake `me`.\n\n**Scopes:** `whiteboard:read:admin`,`whiteboard:read`\n\n**Granular Scopes:** `whiteboard:read:list_whiteboards:admin`,`whiteboard:re[...]",
    "operationId": "ListWhiteboards",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard:read:admin",
       "whiteboard:read",
       "whiteboard:read:list_whiteboards:admin",
       "whiteboard:read:list_whiteboards"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.17.0",
     "x-permissions": [
      "WhiteboardManagement:Read"
     ],
     "x-macro-scopes": [
      "whiteboard:read:admin",
      "whiteboard:read"
     ],
     "x-granular-scopes": [
      "whiteboard:read:list_whiteboards:admin",
      "whiteboard:read:list_whiteboards"
     ]
    }
   },
   "post": {
    "tags": [
     "Document"
    ],
    "summary": "Create a new whiteboard",
    "description": "Use this API to create a new whiteboard for a user.\n\n\n\n**Scopes:** `whiteboard:write`\n\n**Granular Scopes:** `whiteboard:write:whiteboard`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "newWhiteboardCreate",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard:write",
       "whiteboard:write:whiteboard"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [],
     "x-macro-scopes": [
      "whiteboard:write"
     ],
     "x-granular-scopes": [
      "whiteboard:write:whiteboard"
     ]
    }
   }
  },
  "/whiteboards/{whiteboardId}": {
   "get": {
    "tags": [
     "Document"
    ],
    "summary": "Get a whiteboard",
    "description": "Retrieve a whiteboard's information.\n\n**Scopes:** `whiteboard:read:admin`,`whiteboard:read`\n\n**Granular Scopes:** `whiteboard:read:whiteboard:admin`,`whiteboard:read:whiteboard`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GetAWhiteboard",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard:read:admin",
       "whiteboard:read",
       "whiteboard:read:whiteboard:admin",
       "whiteboard:read:whiteboard"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.15.0",
     "x-permissions": [
      "WhiteboardManagement:Read"
     ],
     "x-macro-scopes": [
      "whiteboard:read:admin",
      "whiteboard:read"
     ],
     "x-granular-scopes": [
      "whiteboard:read:whiteboard:admin",
      "whiteboard:read:whiteboard"
     ]
    }
   },
   "put": {
    "tags": [
     "Document"
    ],
    "summary": "Update whiteboard basic information",
    "description": "Use this API to rename a whiteboard, update whiteboard status (locked or unlocked). \n\n**Scopes:** `whiteboard:write:admin`\n\n**Granular Scopes:** `whiteboard:update:whiteboard:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "UpdateAWhiteboardMetadata",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard:write:admin",
       "whiteboard:update:whiteboard:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Edit"
     ],
     "x-macro-scopes": [
      "whiteboard:write:admin"
     ],
     "x-granular-scopes": [
      "whiteboard:update:whiteboard:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Document"
    ],
    "summary": "Delete a whiteboard",
    "description": "Deletes a whiteboard.\n\n**Scopes:** `whiteboard:write:admin`,`whiteboard:write`\n\n**Granular Scopes:** `whiteboard:delete:whiteboard:admin`,`whiteboard:delete:whiteboard`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "DeleteAWhiteboard",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard:write:admin",
       "whiteboard:write",
       "whiteboard:delete:whiteboard:admin",
       "whiteboard:delete:whiteboard"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Edit"
     ],
     "x-macro-scopes": [
      "whiteboard:write:admin",
      "whiteboard:write"
     ],
     "x-granular-scopes": [
      "whiteboard:delete:whiteboard:admin",
      "whiteboard:delete:whiteboard"
     ]
    }
   }
  },
  "/whiteboards/export": {
   "post": {
    "tags": [
     "Export"
    ],
    "summary": "Create whiteboard export",
    "description": " Generates the export for the provided whiteboards. This process will generate a PDF of whiteboard projects along with an audit log, bundling them into a zip file.\n\n**Scopes:** `whiteboard_export:write:admin`,`whiteboard_export:write`\n\n**Granular Scopes:** `whiteboard:write:export`,`whiteboard:write:export:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Createwhiteboardsexport",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_export:write:admin",
       "whiteboard_export:write",
       "whiteboard:write:export",
       "whiteboard:write:export:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardContent:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_export:write:admin",
      "whiteboard_export:write"
     ],
     "x-granular-scopes": [
      "whiteboard:write:export",
      "whiteboard:write:export:admin"
     ]
    }
   }
  },
  "/whiteboards/export/task/{taskId}": {
   "get": {
    "tags": [
     "Export"
    ],
    "summary": "Download whiteboard export",
    "description": "Use this API to download the whiteboard export.\n\n**Scopes:** `whiteboard_content:read:admin`,`whiteboard_content:read`\n\n**Granular Scopes:** `whiteboard:read:export`,`whiteboard:read:export:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Downloadwhiteboardexport",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_content:read:admin",
       "whiteboard_content:read",
       "whiteboard:read:export",
       "whiteboard:read:export:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardContent:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_content:read:admin",
      "whiteboard_content:read"
     ],
     "x-granular-scopes": [
      "whiteboard:read:export",
      "whiteboard:read:export:admin"
     ]
    }
   }
  },
  "/whiteboards/export/task/{taskId}/status": {
   "get": {
    "tags": [
     "Export"
    ],
    "summary": "Get whiteboard export generation status",
    "description": "Use this API to query the status of the whiteboard export generation. Before using this API, confirm that you have invoked the interface for generating the whiteboard file  [**Create whiteboard export**](https://developers.zoom.us/docs/zoom-whiteboard/apis/#operation/Createwhiteboardsexport) and obtained the `task_id`.\n\n**Scopes:** `whiteboard_content:read:admin`,`whiteboard_content:read`\n\n**Granular Scopes:** `whiteboard:read:export`,`whiteboard:read:export:admin`\n\n**[[...]",
    "operationId": "Getwhiteboardexportdatagenerationstatus",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_content:read:admin",
       "whiteboard_content:read",
       "whiteboard:read:export",
       "whiteboard:read:export:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardContent:Read"
     ],
     "x-macro-scopes": [
      "whiteboard_content:read:admin",
      "whiteboard_content:read"
     ],
     "x-granular-scopes": [
      "whiteboard:read:export",
      "whiteboard:read:export:admin"
     ]
    }
   }
  },
  "/whiteboards/{whiteboardId}/share_setting": {
   "patch": {
    "tags": [
     "Settings"
    ],
    "summary": "Update whiteboard share setting",
    "description": "Updates the whiteboard share setting. \n\n\n\n**Scopes:** `whiteboard_share_setting:write:admin`,`whiteboard_share_setting:write`\n\n**Granular Scopes:** `whiteboard:update:share_setting:admin`,`whiteboard:update:share_setting`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "UpdateAWhiteboardShareSetting",
    "security": [
     {
      "openapi_oauth": [
       "whiteboard_share_setting:write:admin",
       "whiteboard_share_setting:write",
       "whiteboard:update:share_setting:admin",
       "whiteboard:update:share_setting"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-fixVersion": "ZDC-DAS 1.14.0",
     "x-permissions": [
      "WhiteboardManagement:Edit"
     ],
     "x-macro-scopes": [
      "whiteboard_share_setting:write:admin",
      "whiteboard_share_setting:write"
     ],
     "x-granular-scopes": [
      "whiteboard:update:share_setting:admin",
      "whiteboard:update:share_setting"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "whiteboard_content:read:admin": "whiteboard_content:read:admin",
       "whiteboard_content:read": "whiteboard_content:read",
       "whiteboard:read:list_sessions": "whiteboard:read:list_sessions",
       "whiteboard:read:list_sessions:admin": "whiteboard:read:list_sessions:admin",
       "whiteboard:read:archived_file": "whiteboard:read:archived_file",
       "whiteboard:read:archived_file:admin": "whiteboard:read:archived_file:admin",
       "whiteboard:read:session": "whiteboard:read:session",
       "whiteboard:read:session:admin": "whiteboard:read:session:admin",
       "whiteboard_collaborator:write:admin": "whiteboard_collaborator:write:admin",
       "whiteboard:write:collaborator:admin": "whiteboard:write:collaborator:admin",
       "whiteboard:update:collaborator:admin": "whiteboard:update:collaborator:admin",
       "whiteboard_collaborator:read:admin": "whiteboard_collaborator:read:admin",
       "whiteboard:read:list_collaborators:admin": "whiteboard:read:list_collaborators:admin",
       "whiteboard:delete:collaborator:admin": "whiteboard:delete:collaborator:admin",
       "whiteboard:read:admin": "whiteboard:read:admin",
       "whiteboard:read": "whiteboard:read",
       "whiteboard:read:list_whiteboards:admin": "whiteboard:read:list_whiteboards:admin",
       "whiteboard:read:list_whiteboards": "whiteboard:read:list_whiteboards",
       "whiteboard:write": "whiteboard:write",
       "whiteboard:write:whiteboard": "whiteboard:write:whiteboard",
       "whiteboard:read:whiteboard:admin": "whiteboard:read:whiteboard:admin",
       "whiteboard:read:whiteboard": "whiteboard:read:whiteboard",
       "whiteboard:write:admin": "whiteboard:write:admin",
       "whiteboard:update:whiteboard:admin": "whiteboard:update:whiteboard:admin",
       "whiteboard:delete:whiteboard:admin": "whiteboard:delete:whiteboard:admin",
       "whiteboard:delete:whiteboard": "whiteboard:delete:whiteboard",
       "whiteboard_export:write:admin": "whiteboard_export:write:admin",
       "whiteboard_export:write": "whiteboard_export:write",
       "whiteboard:write:export": "whiteboard:write:export",
       "whiteboard:write:export:admin": "whiteboard:write:export:admin",
       "whiteboard:read:export": "whiteboard:read:export",
       "whiteboard:read:export:admin": "whiteboard:read:export:admin",
       "whiteboard_share_setting:write:admin": "whiteboard_share_setting:write:admin",
       "whiteboard_share_setting:write": "whiteboard_share_setting:write",
       "whiteboard:update:share_setting:admin": "whiteboard:update:share_setting:admin",
       "whiteboard:update:share_setting": "whiteboard:update:share_setting"
      }
     }
    }
   }
  }
 }
}